### ISSUE TITLE
combining two prompts as a batch to inference models.auto_model with padding embedding

### ISSUE THREAD

**Issue by Jerry00917** [OptimalScale/LMFlow#108]
I pass a list containing two prompts to automodel.encode(). It seems to me that 'model.encode' only support taking one question per time. As I pad two embedding tokens into one tensor, it does not work by simply catting with torch.zeros. It is because zeros represents the string "!"  

So what should I do to correctly cat two token embedding?

Thanks

    prompt = [f"""Input: User{prompt[0]}\n Assistant:""",f"""Input: User{prompt[1]}\n Assistant:"""]
    
    prompt_all = None
    
    #### start padding
    for i in prompt:
        tmp_pro = model.encode(i, return_tensors="pt").to(device=local_rank)
        more_size = 250 - tmp_pro.shape[1]
        tmp_pro = torch.cat((tmp_pro,torch.zeros(1,more_size,dtype=torch.long).cuda()),1)
        if prompt_all == None:
            prompt_all = tmp_pro
        else:
            prompt_all = torch.cat((prompt_all,tmp_pro))
    
    outputs = model.inference(prompt_all, max_new_tokens=250,temperature=0.9, do_sample=False)

**Comment by Jerry00917** [comment]
> We've fixed this issue in our latest main branch. Please check if it works on your end. Thanks! 😄

Thanks for your great support! However, it seems like that is still not ready for multi-batch process inferencing.

prompt_tmp = []
    for i in prompt:
        prompt_tmp.append(f"""Input: User{i}\n Assistant:""")
        
    prompt = prompt_tmp
    
    prompt_all = None
    
    print("length of my batch prompt ",len(prompt))
    
    tmp_pro = model.encode(prompt, return_tensors="pt").to(device=local_rank)
    
    
    exit()


length of my batch prompt  3
  0%|                                                                                                                                                                                                                | 0/6656 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/jerrysun/orglmflow/LMFlow/service/serve.py", line 140, in <module>
    total_ans.extend(inference_many(cur))
  File "/home/jerrysun/orglmflow/LMFlow/service/serve.py", line 78, in inference_many
    tmp_pro = model.encode(prompt, return_tensors="pt").to(device=local_rank)
  File "/home/jerrysun/LMFlow/src/lmflow/models/hf_decoder_model.py", line 334, in encode
    return self.tokenizer.encode(text=input, *args, **kwargs)
  File "/home/jerrysun/anaconda3/envs/lmflow/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2308, in encode
    encoded_inputs = self.encode_plus(
  File "/home/jerrysun/anaconda3/envs/lmflow/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2716, in encode_plus
    return self._encode_plus(
  File "/home/jerrysun/anaconda3/envs/lmflow/lib/python3.9/site-packages/transformers/models/gpt2/tokenization_gpt2_fast.py", line 178, in _encode_plus
    return super()._encode_plus(*args, **kwargs)
  File "/home/jerrysun/anaconda3/envs/lmflow/lib/python3.9/site-packages/transformers/tokenization_utils_fast.py", line 500, in _encode_plus
    batched_output = self._batch_encode_plus(
  File "/home/jerrysun/anaconda3/envs/lmflow/lib/python3.9/site-packages/transformers/models/gpt2/tokenization_gpt2_fast.py", line 168, in _batch_encode_plus
    return super()._batch_encode_plus(*args, **kwargs)
  File "/home/jerrysun/anaconda3/envs/lmflow/lib/python3.9/site-packages/transformers/tokenization_utils_fast.py", line 428, in _batch_encode_plus
    encodings = self._tokenizer.encode_batch(
TypeError: TextEncodeInput must be Union[TextInputSequence, Tuple[InputSequence, InputSequence]]

**Comment by research4pan** [comment]
```
...
File "/home/jerrysun/orglmflow/LMFlow/service/serve.py", line 78, in inference_many
tmp_pro = model.encode(prompt, return_tensors="pt").to(device=local_rank)
File "/home/jerrysun/LMFlow/src/lmflow/models/hf_decoder_model.py", line 334, in encode
return self.tokenizer.encode(text=input, *args, **kwargs)
```
```
This is a bit strange. Since `prompt` is a list, the code should invoke the [logics of batch encode](https://github.com/OptimalScale/LMFlow/blob/main/src/lmflow/models/hf_decoder_model.py#L327), not line 334.

Could you please check the type of `prompt` and see if its type is `list`?
```
isinstance(prompt, list)
```
Thanks! 😄

**Comment by Jerry00917** [comment]
> ```
> ...
> File "/home/jerrysun/orglmflow/LMFlow/service/serve.py", line 78, in inference_many
> tmp_pro = model.encode(prompt, return_tensors="pt").to(device=local_rank)
> File "/home/jerrysun/LMFlow/src/lmflow/models/hf_decoder_model.py", line 334, in encode
> return self.tokenizer.encode(text=input, *args, **kwargs)
> ...
> ```
> 
> 
>      
>   
> 
> This is a bit strange. Since `prompt` is a list, the code should invoke the [logics of batch encode](https://github.com/OptimalScale/LMFlow/blob/main/src/lmflow/models/hf_decoder_model.py#L327), not line 334.
> 
> 
> Could you please check the type of `prompt` and see if its type is `list`?
> 
> 
> ```
> isinstance(prompt, list)
> ```
> 
> 
>      
>   
> 
> Thanks! 😄

Yes! Thank you very much. I solved the problem with tuple and use batch_encode_plus to extract tokens.

**Comment by research4pan** [comment]
You are welcome 😄  Nice to hear that you solved the problem. If you have more suggestions and would like to contribute to our repository, feel free to contact us and create new pull requests. Thanks~
