### ISSUE TITLE
num_train_epochs

### ISSUE THREAD

**Issue by wjn1996** [OptimalScale/LMFlow#111]
Hello, if I want to continual tune a gpt2-base (or large, xl), what's the best ```num_train_epochs``` should set? (The data is default as medical that you have provided.)

**Comment by research4pan** [comment]
Thanks for your interest in LMFlow! We haven't conducted medical experiments in gpt2-base. With llama-7b, we use `num_train_epochs=3`. Hope that answers your question 😄

**Comment by wjn1996** [comment]
Thank you for your response. 

I am training on gpt2 base on my own. We find when batch size=1, gradient_accumulation_steps=4, with 4 v100 gpus, and set epoch as 10. The training process only has about 6000 steps, and the training time only costs 30 min. Is the data from ```download.sh``` is the subset of your project?

**Comment by shizhediao** [comment]
Hi,
Could you check which data you are using?
We release the full medical datasets, which contain about 380K examples. 
I guess you are using `instruction tuning` data.
