### ISSUE TITLE
ImportError: /home/xxxxx/.cache/torch_extensions/py39_cu117/utils/utils.so: cannot open shared object file: No such file or directory [error when run ./scripts/run_finetune.sh]

### ISSUE THREAD

**Issue by Yue-stat** [OptimalScale/LMFlow#117]
Hi, I am trying to run `./scripts/run_finetune.sh`

Could you assist with the following error. Thank you!

`ImportError: /home/xxxxx/.cache/torch_extensions/py39_cu117/utils/utils.so: cannot open shared object file: No such file or directory`

> Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:19<00:00,  9.53s/it]
> [2023-04-04 10:49:48,368] [INFO] [comm.py:652:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
> [2023-04-04 10:49:48,369] [INFO] [logging.py:93:log_dist] [Rank 0] DeepSpeed info: version=0.8.3, git-hash=unknown, git-branch=unknown
> do_ypcall: clnt_call: RPC: Timed out
> [2023-04-04 10:50:32,111] [INFO] [logging.py:93:log_dist] [Rank 0] DeepSpeed Flops Profiler Enabled: False
> [2023-04-04 10:50:32,113] [INFO] [logging.py:93:log_dist] [Rank 0] Creating BF16 optimizer
> [2023-04-04 10:50:32,270] [INFO] [utils.py:829:see_memory_usage] begin bf16_optimizer
> [2023-04-04 10:50:32,270] [INFO] [utils.py:830:see_memory_usage] MA 12.59 GB         Max_MA 12.59 GB         CA 12.59 GB         Max_CA 13 GB
> [2023-04-04 10:50:32,271] [INFO] [utils.py:838:see_memory_usage] CPU Virtual Memory:  used = 80.07 GB, percent = 10.6%
> Using /home/yul184/.cache/torch_extensions/py39_cu117 as PyTorch extensions root...
> Emitting ninja build file /home/yul184/.cache/torch_extensions/py39_cu117/utils/build.ninja...
> Building extension module utils...
> Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
> 1.11.1.git.kitware.jobserver-1
> Loading extension module utils...
> ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
> │ /n/data1/hsph/biostat/celehs/lab/yul184/LMFlow/examples/evaluate.py:34 in <module>               │
> │                                                                                                  │
> │   31 with open (pipeline_args.deepspeed, "r") as f:                                              │
> │   32 │   ds_config = json.load(f)                                                                │
> │   33                                                                                             │
> │ ❱ 34 model = AutoModel.get_model(model_args, tune_strategy='none', ds_config=ds_config)          │
> │   35 dataset = Dataset(data_args)                                                                │
> │   36                                                                                             │
> │   37 evaluator = AutoPipeline.get_pipeline(                                                      │
> │                                                                                                  │
> │ /n/data1/hsph/biostat/celehs/lab/yul184/LMFlow/src/lmflow/models/auto_model.py:14 in get_model   │
> │                                                                                                  │
> │   11 │   @classmethod                                                                            │
> │   12 │   def get_model(self, model_args, *args, **kwargs):                                       │
> │   13 │   │   # TODO (add new models)                                                             │
> │ ❱ 14 │   │   return HFDecoderModel(model_args, *args, **kwargs)                                  │
> │   15                                                                                             │
> │                                                                                                  │
> │ /n/data1/hsph/biostat/celehs/lab/yul184/LMFlow/src/lmflow/models/hf_decoder_model.py:224 in      │
> │ __init__                                                                                         │
> │                                                                                                  │
> │   221 │   │   │   │   )                                                                          │
> │   222 │   │   │                                                                                  │
> │   223 │   │   │   deepspeed.init_distributed()                                                   │
> │ ❱ 224 │   │   │   self.ds_engine = deepspeed.initialize(model=self.backend_model, config_param   │
> │   225 │   │   │   self.ds_engine.module.eval()                                                   │
> │   226 │   │                                                                                      │
> │   227 │   │   elif tune_strategy == 'adapter':                                                   │
> │                                                                                                  │
> │ /home/yul184/.local/lib/python3.9/site-packages/deepspeed/__init__.py:125 in initialize          │
> │                                                                                                  │
> │   122 │   assert model is not None, "deepspeed.initialize requires a model"                      │
> │   123 │                                                                                          │
> │   124 │   if not isinstance(model, PipelineModule):                                              │
> │ ❱ 125 │   │   engine = DeepSpeedEngine(args=args,                                                │
> │   126 │   │   │   │   │   │   │   │    model=model,                                              │
> │   127 │   │   │   │   │   │   │   │    optimizer=optimizer,                                      │
> │   128 │   │   │   │   │   │   │   │    model_parameters=model_parameters,                        │
> │                                                                                                  │
> │ /home/yul184/.local/lib/python3.9/site-packages/deepspeed/runtime/engine.py:347 in __init__      │
> │                                                                                                  │
> │    344 │   │   │   # no optim selected but zero is enabled                                       │
> │    345 │   │   │   self.optimizer = self._configure_zero_optimizer(optimizer=None)               │
> │    346 │   │   elif self.bfloat16_enabled():                                                     │
> │ ❱  347 │   │   │   self.optimizer = self._configure_bf16_optimizer(optimizer=None)               │
> │    348 │   │                                                                                     │
> │    349 │   │   # Bookkeeping for sparse support                                                  │
> │    350 │   │   self.sparse_tensor_module_names = set()                                           │
> │                                                                                                  │
> │ /home/yul184/.local/lib/python3.9/site-packages/deepspeed/runtime/engine.py:1501 in              │
> │ _configure_bf16_optimizer                                                                        │
> │                                                                                                  │
> │   1498 │   │   log_dist('Creating BF16 optimizer', ranks=[0])                                    │
> │   1499 │   │                                                                                     │
> │   1500 │   │   timers = self.timers if self.wall_clock_breakdown() else None                     │
> │ ❱ 1501 │   │   optimizer = BF16_Optimizer(                                                       │
> │   1502 │   │   │   optimizer,                                                                    │
> │   1503 │   │   │   self.param_names,                                                             │
> │   1504 │   │   │   mpu=self.mpu,                                                                 │
> │                                                                                                  │
> │ /home/yul184/.local/lib/python3.9/site-packages/deepspeed/runtime/bf16_optimizer.py:66 in        │
> │ __init__                                                                                         │
> │                                                                                                  │
> │    63 │   │   ]                                                                                  │
> │    64 │   │                                                                                      │
> │    65 │   │   # Load pre-built or JIT compile (un)flatten ops                                    │
> │ ❱  66 │   │   util_ops = UtilsBuilder().load()                                                   │
> │    67 │   │   self.flatten = util_ops.flatten                                                    │
> │    68 │   │   self.unflatten = util_ops.unflatten                                                │
> │    69                                                                                            │
> │                                                                                                  │
> │ /home/yul184/.local/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py:485 in load  │
> │                                                                                                  │
> │   482 │   │   │                                                                                  │
> │   483 │   │   │   return importlib.import_module(self.absolute_name())                           │
> │   484 │   │   else:                                                                              │
> │ ❱ 485 │   │   │   return self.jit_load(verbose)                                                  │
> │   486 │                                                                                          │
> │   487 │   def jit_load(self, verbose=True):                                                      │
> │   488 │   │   if not self.is_compatible(verbose):                                                │
> │                                                                                                  │
> │ /home/yul184/.local/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py:520 in       │
> │ jit_load                                                                                         │
> │                                                                                                  │
> │   517 │   │   │   torch_arch_list = os.environ.get("TORCH_CUDA_ARCH_LIST")                       │
> │   518 │   │   │   os.environ["TORCH_CUDA_ARCH_LIST"] = ""                                        │
> │   519 │   │                                                                                      │
> │ ❱ 520 │   │   op_module = load(                                                                  │
> │   521 │   │   │   name=self.name,                                                                │
> │   522 │   │   │   sources=self.strip_empty_entries(sources),                                     │
> │   523 │   │   │   extra_include_paths=self.strip_empty_entries(extra_include_paths),             │
> │                                                                                                  │
> │ /home/yul184/.local/lib/python3.9/site-packages/torch/utils/cpp_extension.py:1284 in load        │
> │                                                                                                  │
> │   1281 │   │   ...     extra_cflags=['-O2'],                                                     │
> │   1282 │   │   ...     verbose=True)                                                             │
> │   1283 │   '''                                                                                   │
> │ ❱ 1284 │   return _jit_compile(                                                                  │
> │   1285 │   │   name,                                                                             │
> │   1286 │   │   [sources] if isinstance(sources, str) else sources,                               │
> │   1287 │   │   extra_cflags,                                                                     │
> │                                                                                                  │
> │ /home/yul184/.local/lib/python3.9/site-packages/torch/utils/cpp_extension.py:1535 in             │
> │ _jit_compile                                                                                     │
> │                                                                                                  │
> │   1532 │   if is_standalone:                                                                     │
> │   1533 │   │   return _get_exec_path(name, build_directory)                                      │
> │   1534 │                                                                                         │
> │ ❱ 1535 │   return _import_module_from_library(name, build_directory, is_python_module)           │
> │   1536                                                                                           │
> │   1537                                                                                           │
> │   1538 def _write_ninja_file_and_compile_objects(                                                │
> │                                                                                                  │
> │ /home/yul184/.local/lib/python3.9/site-packages/torch/utils/cpp_extension.py:1929 in             │
> │ _import_module_from_library                                                                      │
> │                                                                                                  │
> │   1926 │   │   # https://stackoverflow.com/questions/67631/how-to-import-a-module-given-the-ful  │
> │   1927 │   │   spec = importlib.util.spec_from_file_location(module_name, filepath)              │
> │   1928 │   │   assert spec is not None                                                           │
> │ ❱ 1929 │   │   module = importlib.util.module_from_spec(spec)                                    │
> │   1930 │   │   assert isinstance(spec.loader, importlib.abc.Loader)                              │
> │   1931 │   │   spec.loader.exec_module(module)                                                   │
> │   1932 │   │   return module                                                                     │
> │ in module_from_spec                                                                              │
> │ in create_module                                                                                 │
> │ in _call_with_frames_removed                                                                     │
> ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
> ImportError: /home/yul184/.cache/torch_extensions/py39_cu117/utils/utils.so: cannot open shared object file: No such file or directory
> [2023-04-04 10:50:35,573] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 269843

**Comment by Yue-stat** [comment]
![image](https://user-images.githubusercontent.com/97970714/229833547-24fb5eea-e4db-4944-beb7-e2a134b63e46.png)
![image](https://user-images.githubusercontent.com/97970714/229833599-ae034659-b270-46c4-99e5-11388a06db68.png)
![image](https://user-images.githubusercontent.com/97970714/229833755-63013b85-cd6a-4370-90ee-e7b2afa7c6a5.png)

**Comment by research4pan** [comment]
Thanks for your attention! Normally `.../torch_extensions/py39_cu117/utils/utils.so` will be generated by ninja build. One possible explanation of this missing is that ninja didn't build successfully. You may go to the folder ``.../torch_extensions/py39_cu117/utils`, similar to the solution provided [here](https://github.com/rosinality/stylegan2-pytorch/issues/1#issuecomment-1186088761), and manually run ninja build and get detailed error message. Then according to the error message, we may help you determine the root of this problem. Thanks 😄

**Comment by Yue-stat** [comment]
> manually run ninja build

Thank you for your repy! I did the following. Seems ninja is built successfully? 

```
(lmflow) [yul184@compute-g-17-152 utils]$ ninja
[0/2] c++ -MMD -MF flatten_unflatten.o.d -DTORCH_EXTENSION_NAME=utils -DTORCH...ckages/deepspeed/ops/csrc/utils/flatten_unflatten.cpp -o flatten_unflatten.o

[2/2] c++ flatten_unflatten.o -shared -L/home/yul184/.local/lib/python3.9/site-packages/torch/lib -lc10 -ltorch_cpu -ltorch -ltorch_python -o utils.so
(lmflow) [yul184@compute-g-17-152 utils]$
(lmflow) [yul184@compute-g-17-152 utils]$
(lmflow) [yul184@compute-g-17-152 utils]$ ls
build.ninja  flatten_unflatten.o  utils.so
```

**Comment by research4pan** [comment]
Yes, looks like the build is successful since `utils.so` is generated. You may try to run the script again to see if the error occurs 😄

**Comment by Yue-stat** [comment]
> Yes, looks like the build is successful since `utils.so` is generated. You may try to run the script again to see if the error occurs 😄

Thanks!
