### ISSUE TITLE
environment issues

### ISSUE THREAD

**Issue by sanhaoxueshenglj** [OptimalScale/LMFlow#119]
./scripts/run_finetune_with_lora.sh

Traceback (most recent call last):
  File "********/LMFlow-shizhe-multilingual/scripts/examples/finetune.py", line 21, in <module>
    from lmflow.args import (
ModuleNotFoundError: No module named 'lmflow.args'

Package                  Version
------------------------ -----------
accelerate               0.18.0
aiohttp                  3.8.3
aiosignal                1.3.1
anyio                    3.6.2
appdirs                  1.4.4
async-timeout            4.0.2
attrs                    22.2.0
bce-python-sdk           0.8.73
certifi                  2022.12.7
charset-normalizer       2.1.1
click                    8.1.3
cmake                    3.26.1
colorama                 0.4.6
colorlog                 6.7.0
commonmark               0.9.1
contourpy                1.0.6
cycler                   0.11.0
datasets                 2.10.1
deepspeed                0.8.3
dill                     0.3.4
docker-pycreds           0.4.0
fastapi                  0.88.0
filelock                 3.8.2
Flask                    2.1.3
Flask-Babel              2.0.0
Flask-Cors               3.0.10
fonttools                4.38.0
frozenlist               1.3.3
fsspec                   2023.3.0
fst-pso                  1.8.1
future                   0.18.2
FuzzyTM                  2.0.5
gensim                   4.3.0
gitdb                    4.0.10
GitPython                3.1.31
h11                      0.14.0
hjson                    3.1.0
huggingface-hub          0.13.3
idna                     3.4
importlib-metadata       6.1.0
itsdangerous             2.1.2
jieba                    0.42.1
Jinja2                   3.1.2
joblib                   1.2.0
kiwisolver               1.4.4
lit                      16.0.0
lmflow                   0.0.1.dev0
MarkupSafe               2.1.1
miniful                  0.0.6
mpi4py                   3.1.4
mpmath                   1.3.0
multidict                6.0.4
multiprocess             0.70.12.2
networkx                 3.0
ninja                    1.11.1
numpy                    1.24.2
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-cupti-cu11   11.7.101
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
nvidia-cufft-cu11        10.9.0.58
nvidia-curand-cu11       10.2.10.91
nvidia-cusolver-cu11     11.4.0.1
nvidia-cusparse-cu11     11.7.4.91
nvidia-nccl-cu11         2.14.3
nvidia-nvtx-cu11         11.7.91
packaging                23.0
paddle2onnx              1.0.5
paddlefsl                1.1.0
paddlenlp                2.4.5
pandas                   1.5.2
pathtools                0.1.2
peft                     0.3.0.dev0
pip                      23.0.1
protobuf                 4.22.1
psutil                   5.9.4
py-cpuinfo               9.0.0
pyarrow                  10.0.1
pycryptodome             3.16.0
pydantic                 1.10.2
pyFUME                   0.2.25
Pygments                 2.12.0
pyparsing                3.0.9
python-dateutil          2.8.2
pytz                     2022.7
PyYAML                   6.0
rec-train                2.0.0
regex                    2023.3.23
requests                 2.28.2
responses                0.18.0
rich                     12.6.0
sentencepiece            0.1.96
sentry-sdk               1.19.0
seqeval                  1.2.2
setproctitle             1.3.2
setuptools               65.6.3
simpful                  2.9.0
six                      1.16.0
smmap                    5.0.0
sniffio                  1.3.0
starlette                0.22.0
sympy                    1.11.1
threadpoolctl            3.1.0
tokenizers               0.13.2
torch                    2.0.0
tqdm                     4.65.0
transformers             4.28.0.dev0
triton                   2.0.0
trl                      0.4.2.dev0
typer                    0.7.0
typing_extensions        4.4.0
urllib3                  1.26.15
uvicorn                  0.20.0
visualdl                 2.4.1
wandb                    0.14.0
Werkzeug                 2.1.2
wheel                    0.38.4
xxhash                   3.1.0
yarl                     1.8.2
zipp                     3.11.0

**Comment by research4pan** [comment]
Thanks for your interest in LMFlow! Please run `pip install -e .` to install our package. The full installation process is available in (setup section of README)[https://github.com/OptimalScale/LMFlow#1setup]. Thanks 😄
