### ISSUE TITLE
ValueError: Target modules ['q_proj', 'v_proj'] not found in the base model. Please check the target modules and try again.

### ISSUE THREAD

**Issue by pckennethma** [OptimalScale/LMFlow#125]
Hello,

Could you consider revise [line 165](https://github.com/OptimalScale/LMFlow/blob/main/src/lmflow/models/hf_decoder_model.py#L165) in hf_decoder_model.py? This could cause `ValueError: Target modules ['q_proj', 'v_proj'] not found in the base model. Please check the target modules and try again.` when finetuning other models (e.g., Bloom) with LoRA. You may simply remove this line and PEFT would automcatically decide proper target modules.

**Comment by shizhediao** [comment]
Hi, 
Thanks for your suggestion!
We are going to fix this issue. Do you want to open a PR? Otherwise, we can do it later.

Thanks!

**Comment by pckennethma** [comment]
Sure! I will create a PR.
