### ISSUE TITLE
No module named 'lmflow.args`?

### ISSUE THREAD

**Issue by EricaZheng** [OptimalScale/LMFlow#142]
Dear All,

Please advice how to fix this:
`ModuleNotFoundError: No module named 'lmflow.args`

Thank you

**Comment by research4pan** [comment]
Thanks for your attention! According to [README.md](https://github.com/OptimalScale/LMFlow#1setup), you may install the package as follows:
```
git clone https://github.com/OptimalScale/LMFlow.git
cd LMFlow
conda create -n lmflow python=3.9 -y
conda activate lmflow
conda install mpi4py
pip install -e .
```
This will install our package and make `lmflow.args` accessible. A [similar issue](https://github.com/OptimalScale/LMFlow/issues/136#issuecomment-1497761830) has been reported before, you may refer to that as well. Thanks 😄
