### ISSUE TITLE
远程model参数默认未开启，无法直接使用hugging face model

### ISSUE THREAD

**Issue by breaking153** [OptimalScale/LMFlow#147]
![图片](https://user-images.githubusercontent.com/49428332/230319558-f3ae0a7d-ccdc-4968-9593-d421be9de1c4.png)

**Comment by shizhediao** [comment]
Hi,
We have support ChatGLM inference. Please try this script `https://github.com/OptimalScale/LMFlow/blob/main/scripts/run_chatbot_chatglm.sh`

Thank you!

**Comment by breaking153** [comment]
wow,that's pretty good,thanks for all of you guys!!!!
