### ISSUE TITLE
144.214.54.164:5000 not work

### ISSUE THREAD

**Issue by jcs130** [OptimalScale/LMFlow#164]
Connecting to 144.214.54.164:5000... connected.
HTTP request sent, awaiting response... No data received.

**Comment by research4pan** [comment]
Hi, our checkpoint/data download service is temporarily unavailable due to high capacity. We are deploying a new server for that. Sorry for the inconvenience. Thanks for your understanding 🙏

**Comment by shizhediao** [comment]
The server has been fixed and the download service is now normal. Thank you for your patience.
