### ISSUE TITLE
binascii.Error: Incorrect padding while trying to run 'run_finetune.sh'

### ISSUE THREAD

**Issue by garrett-yiran-zhong** [OptimalScale/LMFlow#200]
I'm using ubuntu 22.04, trying to run 'run_finetune.sh', all step is follow the quick start, quite confuse about the base64 error.

Here is the error log:
[2023-04-10 20:53:48,405] [INFO] [comm.py:652:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
Traceback (most recent call last):
  File "/home/xxx/lmflow/LMFlow/scripts/examples/finetune.py", line 70, in <module>
    main()
  File "/home/xxx/lmflow/LMFlow/scripts/examples/finetune.py", line 43, in main
    model_args, data_args, pipeline_args = parser.parse_args_into_dataclasses()
  File "/home/xxx/anaconda3/envs/lmflow/lib/python3.9/site-packages/transformers/hf_argparser.py", line 332, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 109, in __init__
  File "/home/x/anaxxconda3/envs/lmflow/lib/python3.9/site-packages/transformers/training_args.py", line 1414, in __post_init__
    self.hf_deepspeed_config = HfTrainerDeepSpeedConfig(self.deepspeed)
  File "/home/xxx/anaconda3/envs/lmflow/lib/python3.9/site-packages/transformers/deepspeed.py", line 77, in __init__
    super().__init__(config_file_or_dict)
  File "/home/xxx/anaconda3/envs/lmflow/lib/python3.9/site-packages/transformers/deepspeed.py", line 67, in __init__
    super().__init__(config_file_or_dict)
  File "/home/xxx/anaconda3/envs/lmflow/lib/python3.9/site-packages/accelerate/utils/deepspeed.py", line 52, in __init__
    config_decoded = base64.urlsafe_b64decode(config_file_or_dict).decode("utf-8")
  File "/home/xxx/anaconda3/envs/lmflow/lib/python3.9/base64.py", line 133, in urlsafe_b64decode
    return b64decode(s)
  File "/home/xxx/anaconda3/envs/lmflow/lib/python3.9/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

**Comment by research4pan** [comment]
Hi! Thanks for your interest in LMFlow! Looks like the format of the provided `ds_config_xxx.json` is incorrect. Could you please provide the used the `ds_config_xxx.json` file? My guess is that there is an extra tab in the config. Thanks 😄

**Comment by garrett-yiran-zhong** [comment]
> Hi! Thanks for your interest in LMFlow! Looks like the format of the provided `ds_config_xxx.json` is incorrect. Could you please provide the used the `ds_config_xxx.json` file? My guess is that there is an extra tab in the config. Thanks 😄

Thank for reply, here is the config.json

{
    "fp16": {
        "enabled": "auto",
        "loss_scale": 0,
        "loss_scale_window": 1000,
        "initial_scale_power": 16,
        "hysteresis": 2,
        "min_loss_scale": 1
    },

    "bf16": {
        "enabled": "auto"
    },

    "optimizer": {
        "type": "AdamW",
        "params": {
            "lr": "auto",
            "betas": "auto",
            "eps": "auto",
            "weight_decay": "auto"
        }
    },

    "zero_optimization": {
        "stage": 3,
        "offload_optimizer": {
            "device": "cpu",
            "pin_memory": true
        },
        "offload_param": {
            "device": "cpu",
            "pin_memory": true
        },
        "overlap_comm": true,
        "contiguous_gradients": true,
        "sub_group_size": 1e9,
        "reduce_bucket_size": "auto",
        "stage3_prefetch_bucket_size": "auto",
        "stage3_param_persistence_threshold": "auto",
        "stage3_max_live_parameters": 1e9,
        "stage3_max_reuse_distance": 1e9,
        "stage3_gather_16bit_weights_on_model_save": true
    },

    "gradient_accumulation_steps": "auto",
    "gradient_clipping": "auto",
    "steps_per_print": 2000,
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "wall_clock_breakdown": false
}

**Comment by Dominic789654** [comment]
I encountered the same issue when running this project on some servers. My solution was to change the path of the deepspeed config, which is `--deepspeed` in the shell, to an absolute path like `--deepspeed /home/user/LMFlow/configs/ds_config_zero2.json`. The problem in my case was that when I submitted the project to the servers, the location of the config files changed. As a result, the HuggingFace arguments function couldn't find `configs/ds_config_zero2.json`, and the arguments function treader `configs/ds_config_zero2.json` as a path, the the function try to find config files under this path, finally causing this error.

You can try changing the `--deepspeed` config file path to an absolute path to resolve this issue.

**Comment by garrett-yiran-zhong** [comment]
> I encountered the same issue when running this project on some servers. My solution was to change the path of the deepspeed config, which is `--deepspeed` in the shell, to an absolute path like `--deepspeed /home/user/LMFlow/configs/ds_config_zero2.json`. The problem in my case was that when I submitted the project to the servers, the location of the config files changed. As a result, the HuggingFace arguments function couldn't find `configs/ds_config_zero2.json`, and the arguments function will treat `configs/ds_config_zero2.json` as a path, the function tries to find config files under this path, finally causing this error.
> 
> You can try changing the `--deepspeed` config file path to an absolute path to resolve this issue.

Thanks for the solution, i will try later.
