### ISSUE TITLE
Question about the task tuning

### ISSUE THREAD

**Issue by Flow3rDown** [OptimalScale/LMFlow#222]
Hi,
Nice work! But I have a question about the task tuning. I saw in the documentation that you applied task tuning on two PubMedQA and MedMCQA datasets. Do you train separately on the two datasets or mix the two datasets and train once?

**Comment by research4pan** [comment]
Thanks for your interest in LMFlow! We mix the two datasets and train once. Hope that answers your question~Thanks 😄

**Comment by Flow3rDown** [comment]
Fine! Thanks for your answer.
