### ISSUE TITLE
message always return "There is something wrong, please query again"

### ISSUE THREAD

**Issue by reonard** [OptimalScale/LMFlow#236]
I am a beginner and I just started the web server locally. The server started successfully and I could access the webpage through http://127.0.0.1:5000. However, it keeps returning the message "There is something wrong, please query again". Am I missing something?

> Using /home/xxxx/.cache/torch_extensions/py310_cu117 as PyTorch extensions root...
> 
> No modifications detected for re-loaded extension module utils, skipping build step...
> Loading extension module utils...
> Time to load utils op: 0.00028252601623535156 seconds
>  * Serving Flask app 'app'
>  * Debug mode: off
> WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
>  * Running on http://127.0.0.1:5000
> Press CTRL+C to quit
> 127.0.0.1 - - [16/Apr/2023 02:56:18] "GET / HTTP/1.1" 200 -
> 127.0.0.1 - - [16/Apr/2023 02:56:18] "GET /static/utils/vue-spinner.js HTTP/1.1" 304 -
> 127.0.0.1 - - [16/Apr/2023 02:56:18] "GET /static/assets/logo.png HTTP/1.1" 304 -
> 127.0.0.1 - - [16/Apr/2023 02:56:19] "GET /static/assets/background.png HTTP/1.1" 304 -
> 127.0.0.1 - - [16/Apr/2023 02:56:25] "POST /predict HTTP/1.1" 200 -
> 127.0.0.1 - - [16/Apr/2023 02:56:46] "POST /predict HTTP/1.1" 200 -
> 127.0.0.1 - - [16/Apr/2023 02:56:54] "POST /predict HTTP/1.1" 200 -

**Comment by research4pan** [comment]
Thanks for your interest in LMFlow! Looks like some exceptions occur inside the service. You may remove the `try...except... ` exception capture logics starting from [service/app.py](https://github.com/OptimalScale/LMFlow/blob/main/service/app.py#L40) and view the detailed error message, i.e. remove line 40/58/59 and run the service again. We can then check that for you. Thanks 😄

**Comment by reonard** [comment]
> Thanks for your interest in LMFlow! Looks like some exceptions occur inside the service. You may remove the `try...except... ` exception capture logics starting from [service/app.py](https://github.com/OptimalScale/LMFlow/blob/main/service/app.py#L40) and view the detailed error message, i.e. remove line 40/58/59 and run the service again. We can then check that for you. Thanks smile

thanks a lot. Now I can see the exception, but still have no idea how to fix it, any cue?  thanks

```
Traceback (most recent call last):
  File "/app/ai/LMFlow/service/./app.py", line 55, in predict
    outputs = model.inference(inputs, max_new_tokens=150,temperature=0.0, do_sample=False)
  File "/app/ai/LMFlow/src/lmflow/models/hf_decoder_model.py", line 406, in inference
    outputs = self.ds_engine.module.generate(
  File "/app/anaconda3/envs/lmflow/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/app/anaconda3/envs/lmflow/lib/python3.10/site-packages/transformers/generation/utils.py", line 1437, in generate
    return self.greedy_search(
  File "/app/anaconda3/envs/lmflow/lib/python3.10/site-packages/transformers/generation/utils.py", line 2248, in greedy_search
    outputs = self(
  File "/app/anaconda3/envs/lmflow/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/app/anaconda3/envs/lmflow/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/app/anaconda3/envs/lmflow/lib/python3.10/site-packages/transformers/models/gpt_neo/modeling_gpt_neo.py", line 741, in forward
    transformer_outputs = self.transformer(
  File "/app/anaconda3/envs/lmflow/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/app/anaconda3/envs/lmflow/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/app/anaconda3/envs/lmflow/lib/python3.10/site-packages/transformers/models/gpt_neo/modeling_gpt_neo.py", line 621, in forward
    outputs = block(
  File "/app/anaconda3/envs/lmflow/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/app/anaconda3/envs/lmflow/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/app/anaconda3/envs/lmflow/lib/python3.10/site-packages/transformers/models/gpt_neo/modeling_gpt_neo.py", line 326, in forward
    attn_outputs = self.attn(
  File "/app/anaconda3/envs/lmflow/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/app/anaconda3/envs/lmflow/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/app/anaconda3/envs/lmflow/lib/python3.10/site-packages/transformers/models/gpt_neo/modeling_gpt_neo.py", line 278, in forward
    return self.attention(
  File "/app/anaconda3/envs/lmflow/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/app/anaconda3/envs/lmflow/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/app/anaconda3/envs/lmflow/lib/python3.10/site-packages/transformers/models/gpt_neo/modeling_gpt_neo.py", line 222, in forward
    query = self.q_proj(hidden_states)
  File "/app/anaconda3/envs/lmflow/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/app/anaconda3/envs/lmflow/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/app/anaconda3/envs/lmflow/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`
127.0.0.1 - - [16/Apr/2023 20:23:31] "POST /predict HTTP/1.1" 200 -
```

**Comment by reonard** [comment]
attached my env info by runing 'python -m torch.utils.collect_env'. the GPU is 4080 laptop ver

> Collecting environment information...
> PyTorch version: 2.0.0+cu117
> Is debug build: False
> CUDA used to build PyTorch: 11.7
> ROCM used to build PyTorch: N/A
> 
> OS: Ubuntu 22.04.2 LTS (x86_64)
> GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
> Clang version: Could not collect
> CMake version: version 3.26.3
> Libc version: glibc-2.35
> 
> Python version: 3.10.10 (main, Mar 21 2023, 18:45:11) [GCC 11.2.0] (64-bit runtime)
> Python platform: Linux-5.19.0-38-generic-x86_64-with-glibc2.35
> Is CUDA available: True
> CUDA runtime version: Could not collect
> CUDA_MODULE_LOADING set to: LAZY
> GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4080 Laptop GPU
> Nvidia driver version: 525.105.17
> cuDNN version: Could not collect
> HIP runtime version: N/A
> MIOpen runtime version: N/A
> Is XNNPACK available: True
> 
> CPU:
> Architecture:                    x86_64
> CPU op-mode(s):                  32-bit, 64-bit
> Address sizes:                   39 bits physical, 48 bits virtual
> Byte Order:                      Little Endian
> CPU(s):                          32
> On-line CPU(s) list:             0-31
> Vendor ID:                       GenuineIntel
> Model name:                      13th Gen Intel(R) Core(TM) i9-13980HX
> CPU family:                      6
> Model:                           183
> Thread(s) per core:              2
> Core(s) per socket:              24
> Socket(s):                       1
> Stepping:                        1
> CPU max MHz:                     5600.0000
> CPU min MHz:                     800.0000
> BogoMIPS:                        4838.40
> Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves split_lock_detect avx_vnni dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req hfi umip pku ospke waitpkg gfni vaes vpclmulqdq rdpid movdiri movdir64b fsrm md_clear serialize arch_lbr ibt flush_l1d arch_capabilities
> Virtualization:                  VT-x
> L1d cache:                       896 KiB (24 instances)
> L1i cache:                       1.3 MiB (24 instances)
> L2 cache:                        32 MiB (12 instances)
> L3 cache:                        36 MiB (1 instance)
> NUMA node(s):                    1
> NUMA node0 CPU(s):               0-31
> Vulnerability Itlb multihit:     Not affected
> Vulnerability L1tf:              Not affected
> Vulnerability Mds:               Not affected
> Vulnerability Meltdown:          Not affected
> Vulnerability Mmio stale data:   Not affected
> Vulnerability Retbleed:          Not affected
> Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
> Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
> Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
> Vulnerability Srbds:             Not affected
> Vulnerability Tsx async abort:   Not affected
> 
> Versions of relevant libraries:
> [pip3] numpy==1.24.2
> [pip3] torch==2.0.0
> [conda] numpy                     1.24.2                   pypi_0    pypi
> [conda] torch                     2.0.0                    pypi_0    pypi

**Comment by research4pan** [comment]
Thanks for providing more details! According to [this issue](https://github.com/OptimalScale/LMFlow/issues/44), it can be caused by `--use_ram_optimized_load`, you may disable that by replacing this line with
```
model_args = ModelArguments(model_name_or_path=model_name_or_path, use_ram_optimized_load=False)
```
If that doesn't work, then it normally means the GPU memory is not enough. You may consider use a smaller model or run on a server with larger GPU memory.

Thanks~

**Comment by reonard** [comment]
> 



> Thanks for providing more details! According to [this issue](https://github.com/OptimalScale/LMFlow/issues/44), it can be caused by `--use_ram_optimized_load`, you may disable that by replacing this line with
> 
> ```
> model_args = ModelArguments(model_name_or_path=model_name_or_path, use_ram_optimized_load=False)
> ```
> 
> If that doesn't work, then it normally means the GPU memory is not enough. You may consider using a smaller model or running on a server with larger GPU memory.
> 
> Thanks~

it works~ thanks a lot :)

**Comment by shizhediao** [comment]
ok, great.
