### ISSUE TITLE
answer_type to get output yes/no

### ISSUE THREAD

**Issue by Yue-stat** [OptimalScale/LMFlow#254]
When I run evaluation, if I use   `--answer_type text`, I would get result in the attached pic.
![f98d2e134a8e513a3718afe0548ce78](https://user-images.githubusercontent.com/97970714/232420284-37fff38d-f3ae-4859-bd9f-c02a45090341.png)

I was wondering if there is any `answer_type ` I can put here to get output only **yes/no**.

**Comment by Yue-stat** [comment]
> Hi, Thanks for your attention. You may refer to the code here: https://github.com/OptimalScale/LMFlow/blob/main/src/lmflow/utils/data_utils.py#L119 For example, setting `--answer_type strategyqa` is similar to your task.

Thanks!

**Comment by shizhediao** [comment]
Hope it helps. If you have further questions, feel free to reopen this issue or create a new issue.

Thanks!
