### ISSUE TITLE
为什么我下载数据集，出现这种错误

### ISSUE THREAD

**Issue by wunengwu** [OptimalScale/LMFlow#255]
download.sh: line 2: $'\r': command not found
download.sh: line 3: syntax error near unexpected token `$'{\r''
'ownload.sh: line 3: `function main() {

请问这种怎么解决？

**Comment by shizhediao** [comment]
你好，请问使用的是什么系统，以及执行的命令是什么。
可以试一下这个命令`bash download.sh all` 
---------------
Hello, may I ask what system you are using and what command you are executing? You can try running this command: `bash download.sh all`.

**Comment by wunengwu** [comment]
> 你好，请问使用的是什么系统，以及执行的命令是什么。 可以试一下这个命令`bash download.sh all`
> 
> Hello, may I ask what system you are using and what command you are executing? You can try running this command: `bash download.sh all`.

我在服务器里面运行这个项目，属于Linux系统，这个命令我试了，可是失败了

**Comment by shizhediao** [comment]
> > 你好，请问使用的是什么系统，以及执行的命令是什么。 可以试一下这个命令`bash download.sh all`
> > Hello, may I ask what system you are using and what command you are executing? You can try running this command: `bash download.sh all`.
> 
> 我在服务器里面运行这个项目，属于Linux系统，这个命令我试了，可是失败了

可以贴一下更多的信息吗，比如整个命令行的截图。

**Comment by wunengwu** [comment]
> > > 你好，请问使用的是什么系统，以及执行的命令是什么。 可以试一下这个命令`bash download.sh all`
> > > Hello, may I ask what system you are using and what command you are executing? You can try running this command: `bash download.sh all`.
> > 
> > 
> > 我在服务器里面运行这个项目，属于Linux系统，这个命令我试了，可是失败了
> 
> 可以贴一下更多的信息吗，比如整个命令行的截图。我帮您看一下，谢谢。
> 
> Can you please provide more information, such as a screenshot of the entire command line? I will take a look for you. Thank you.



> > > 你好，请问使用的是什么系统，以及执行的命令是什么。 可以试一下这个命令`bash download.sh all`
> > > Hello, may I ask what system you are using and what command you are executing? You can try running this command: `bash download.sh all`.
> > 
> > 
> > 我在服务器里面运行这个项目，属于Linux系统，这个命令我试了，可是失败了
> 
> 可以贴一下更多的信息吗，比如整个命令行的截图。我帮您看一下，谢谢。
> 
> Can you please provide more information, such as a screenshot of the entire command line? I will take a look for you. Thank you.
![wrong](https://user-images.githubusercontent.com/129244270/232980533-1073b95b-7649-4e9b-b439-6aea239e198c.png)
![Snipaste_2023-04-19_14-00-42](https://user-images.githubusercontent.com/129244270/232980614-cd413bcd-9420-4018-b934-2c8d1360221a.png)
像这样的问题
