### ISSUE TITLE
希望复现（https://lmflow.com/chat）中的聊天效果。

### ISSUE THREAD

**Issue by 2415383726** [OptimalScale/LMFlow#256]
我希望能得到(  https://lmflow.com/chat  )中的聊天效果，请问有公布的lora吗？尝试了几个，结果都不对。
app.py设置如下：
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/70671786/232515776-9c16398c-257c-4587-8407-3362dd91cf9f.png">
结果如下：
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/70671786/232517917-0caffcbf-7185-410d-9232-749df6245dd6.png">

**Comment by shizhediao** [comment]
你好，
我们会于今明两天公布一些新训练完成的模型。这些模型在更多高质量的数据集上进行训练。7B模型已经完成部署上线，会尽快开源。到时会告知您，感谢关注！

-----
Hi,
We will release some newly completed training models in the next two days. These models have been trained on more high-quality datasets. The 7B model has been deployed and will be open-sourced soon. We will inform you when it happens. Thank you for your attention!
