### ISSUE TITLE
Mismatch results in the RAFT paper

### ISSUE THREAD

**Issue by Dr-Corgi** [OptimalScale/LMFlow#259]
可以解释一下RAFT论文里Table2和Figure 1右图的关系吗？
看Table 2的结果，PPO在相同perplexity下，mean reward是更高的；
看Figure 1右图的结果，结论是相反的；

两个图表放在一起看，这两个数据是不是有一个填反了？

**Comment by hendrydong** [comment]
感谢您的指出。我们再次确认了早些时候的版本，发现是表格修改格式的时候的typo。我们会改到paper中间去。
以下是原始结果。


![191361681793811_ pic](https://user-images.githubusercontent.com/18676401/232675287-5bf0308c-1058-4543-b686-6b09d50a83e2.jpg)

**Comment by Dr-Corgi** [comment]
ok。我还有一个疑问就是Equation(1)和Algorithm(1)的关系是...?
从3.1 Problem Setup部分来看这里引入了expert generator G(x)，我理解这里应该是用G(x)实现了对于quality的约束；
但是从Algorithm(1)的内容来看，G_t既可以是G(x)也可以是g(w,x)，两者之间似乎相对是独立的，和3.1部分描述的似乎没有太大关系。

换句话说，Equation(2)中的Q(w)在Algorithm(1)中起到什么作用？
Equation(2)和Algorithm(1)中的λ似乎扮演的也是不同的角色？

谢谢

**Comment by hendrydong** [comment]
Eq.1中 reward maximization 与ranking等价，当没有Q的时候，模型会收敛到最大r(x,y)的response。
引入Q之后模型不会collapse，具体而言KL(p_G||p_g)等价于从G里采样，对g做MLE，而reward maximization和原始模型采样的权重为lambda：1。

**Comment by Dr-Corgi** [comment]
好的，谢谢！
