### ISSUE TITLE
Does it or will it support Vicuna-13b-v1.1 finetuning?

### ISSUE THREAD

**Issue by ghost** [OptimalScale/LMFlow#265]
Thanks for creating such an amazing project.

Vicuna-13b-v1.1 seems to achieve impressive performance in tasks in multiple languages. I believe it would be a good idea to conduct further fine-tuning based on it. So, will this project support Vicuna-13b-v1.1 finetuning later?

**Comment by shizhediao** [comment]
Hi,
Thank you very much for your interest in our work.
We will support vicuna-13b-v1.1 very soon.
