### ISSUE TITLE
Is there full tuning demo or script?

### ISSUE THREAD

**Issue by ticoAg** [OptimalScale/LMFlow#271]
> [2023-03-27] Support full tuning and lora tuning for all decoder models.

Notice that 3.27 update this record, but not found example script to start full tuning, is there some readme guide? thanks.

**Comment by shizhediao** [comment]
Hi if you want to train the full model, please refer to the script https://github.com/OptimalScale/LMFlow/blob/main/scripts/run_finetune.sh

**Comment by ticoAg** [comment]
ok 3q.
