### ISSUE TITLE
Install error, No matching distribution found for datasets==2.10.1

### ISSUE THREAD

**Issue by 2718564960** [OptimalScale/LMFlow#276]
git clone https://github.com/OptimalScale/LMFlow.git
cd LMFlow
conda create -n lmflow python=3.9 -y
conda activate lmflow
conda install mpi4py
pip install -e .

------------log

pip install -e .
Looking in indexes: https://pypi.shopee.io/
Obtaining file:///data/lining/LMFlow
  Preparing metadata (setup.py) ... done
Collecting peft@ git+https://github.com/huggingface/peft.git@deff03f2c251534fffd2511fc2d440e84cc54b1b
  Cloning https://github.com/huggingface/peft.git (to revision deff03f2c251534fffd2511fc2d440e84cc54b1b) to /tmp/pip-install-ameh7xm8/peft_ebdd4fbd3b6c4b7c8a5265d628835a21
  Running command git clone --quiet https://github.com/huggingface/peft.git /tmp/pip-install-ameh7xm8/peft_ebdd4fbd3b6c4b7c8a5265d628835a21
  Running command git rev-parse -q --verify 'sha^deff03f2c251534fffd2511fc2d440e84cc54b1b'
  Running command git fetch -q https://github.com/huggingface/peft.git deff03f2c251534fffd2511fc2d440e84cc54b1b
  Running command git checkout -q deff03f2c251534fffd2511fc2d440e84cc54b1b
  Resolved https://github.com/huggingface/peft.git to commit deff03f2c251534fffd2511fc2d440e84cc54b1b
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting trl@ git+https://github.com/lvwerra/trl.git#egg=trl-0.4.1
  Cloning https://github.com/lvwerra/trl.git to /tmp/pip-install-ameh7xm8/trl_db26604132b640f894e10a2ce0d88d93
  Running command git clone --quiet https://github.com/lvwerra/trl.git /tmp/pip-install-ameh7xm8/trl_db26604132b640f894e10a2ce0d88d93
  Resolved https://github.com/lvwerra/trl.git to commit ce37eadcfa22f2a3c25422411a586b8f593e3e6e
  Preparing metadata (setup.py) ... done
Collecting transformers@ git+https://github.com/huggingface/transformers@c612628045822f909020f7eb6784c79700813eda
  Cloning https://github.com/huggingface/transformers (to revision c612628045822f909020f7eb6784c79700813eda) to /tmp/pip-install-ameh7xm8/transformers_156a9169763e464d8b1c147736555692
  Running command git clone --quiet https://github.com/huggingface/transformers /tmp/pip-install-ameh7xm8/transformers_156a9169763e464d8b1c147736555692
  Running command git rev-parse -q --verify 'sha^c612628045822f909020f7eb6784c79700813eda'
  Running command git fetch -q https://github.com/huggingface/transformers c612628045822f909020f7eb6784c79700813eda
  Running command git checkout -q c612628045822f909020f7eb6784c79700813eda
  Resolved https://github.com/huggingface/transformers to commit c612628045822f909020f7eb6784c79700813eda
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy==1.24.2 in /data/lining/.conda/envs/lining39/lib/python3.9/site-packages (from lmflow==0.0.1) (1.24.2)
ERROR: Could not find a version that satisfies the requirement datasets==2.10.1 (from lmflow) (from versions: 0.0.9, 1.0.0, 1.0.1, 1.0.2, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.2.0, 1.2.1, 1.3.0, 1.4.0, 1.4.1, 1.5.0, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.8.0, 1.9.0, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 1.13.2, 1.13.3, 1.14.0, 1.15.0, 1.15.1, 1.16.0, 1.16.1, 1.17.0, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 2.0.0, 2.1.0, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.3.2, 2.4.0, 2.5.0, 2.5.1, 2.5.2, 2.6.0, 2.6.1, 2.6.2, 2.7.0, 2.7.1, 2.8.0, 2.9.0)
ERROR: No matching distribution found for datasets==2.10.1

**Comment by shizhediao** [comment]
what is the pip source? Could you try different pip source?

**Comment by 2718564960** [comment]
I use https://pypi.org/project/datasets/2.10.1/#files  fix it.

**Comment by 2718564960** [comment]
> what is the pip source? Could you try different pip source?

Yes, thank you. It works now~

**Comment by shizhediao** [comment]
great!
