### ISSUE TITLE
运行./scripts/run_chatbot.sh pinkmanlove/llama-7b-hf ./output_models/robin-7b/后，对话出现错误

### ISSUE THREAD

**Issue by LiuMingwu** [OptimalScale/LMFlow#289]
![image](https://user-images.githubusercontent.com/37980561/233830114-6df07967-6351-4af9-acab-13e342d9b3f3.png)
![image](https://user-images.githubusercontent.com/37980561/233830137-5700c7af-749a-4613-acf5-74c4fdb9116c.png)

**Comment by shizhediao** [comment]
目前的信息不足以定位问题，请问是否还有其他报错信息可以提供，也可以检查一下安装的环境是否正确。谢谢

-------
The current information is not sufficient to locate the problem. Is there any other error information that can be provided, or can we check if the installation environment is correct? Thank you.

**Comment by LiuMingwu** [comment]
这是我目前conda list，请问是否是环境问题所致？
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
accelerate                0.18.0                   pypi_0    pypi
aiohttp                   3.8.4                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
attrs                     22.2.0                   pypi_0    pypi
blas                      1.0                         mkl  
brotlipy                  0.7.0           py39h27cfd23_1003  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2023.01.10           h06a4308_0  
cchardet                  2.1.7                    pypi_0    pypi
certifi                   2022.12.7        py39h06a4308_0  
cffi                      1.15.1           py39h5eee18b_3  
chardet                   5.1.0                    pypi_0    pypi
charset-normalizer        3.1.0                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
cmake                     3.26.1                   pypi_0    pypi
cpm-kernels               1.0.11                   pypi_0    pypi
cryptography              39.0.1           py39h9ce1e76_0  
cudatoolkit               11.3.1               h2bc3f7f_2  
datasets                  2.10.1                   pypi_0    pypi
deepspeed                 0.8.3                    pypi_0    pypi
dill                      0.3.6                    pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
filelock                  3.10.7                   pypi_0    pypi
flask                     2.2.3                    pypi_0    pypi
flask-cors                3.0.10                   pypi_0    pypi
flit-core                 3.8.0            py39h06a4308_0  
freetype                  2.12.1               h4a9f257_0  
frozenlist                1.3.3                    pypi_0    pypi
fsspec                    2023.3.0                 pypi_0    pypi
giflib                    5.2.1                h5eee18b_3  
gitdb                     4.0.10                   pypi_0    pypi
gitpython                 3.1.31                   pypi_0    pypi
gmp                       6.2.1                h295c915_3  
gnutls                    3.6.15               he1e5248_0  
hjson                     3.1.0                    pypi_0    pypi
huggingface-hub           0.13.3                   pypi_0    pypi
icetk                     0.0.7                    pypi_0    pypi
idna                      3.4              py39h06a4308_0  
importlib-metadata        6.1.0                    pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561  
itsdangerous              2.1.2                    pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
jpeg                      9e                   h5eee18b_1  
lame                      3.100                h7b6447c_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.38                 h1181459_1  
lerc                      3.0                  h295c915_0  
libdeflate                1.17                 h5eee18b_0  
libffi                    3.4.2                h6a678d5_6  
libgcc-ng                 11.2.0               h1234567_1  
libgfortran-ng            7.5.0               ha8ba4b0_17  
libgfortran4              7.5.0               ha8ba4b0_17  
libgomp                   11.2.0               h1234567_1  
libiconv                  1.16                 h7f8727e_2  
libidn2                   2.3.2                h7f8727e_0  
libpng                    1.6.39               h5eee18b_0  
libstdcxx-ng              11.2.0               h1234567_1  
libtasn1                  4.16.0               h27cfd23_0  
libtiff                   4.5.0                h6a678d5_2  
libunistring              0.9.10               h27cfd23_0  
libwebp                   1.2.4                h11a3e52_1  
libwebp-base              1.2.4                h5eee18b_1  
lit                       16.0.0                   pypi_0    pypi
lz4-c                     1.9.4                h6a678d5_0  
markupsafe                2.1.2                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py39h7f8727e_0  
mkl_fft                   1.3.1            py39hd3c417c_0  
mkl_random                1.2.2            py39h51133e4_0  
mpi                       1.0                       mpich  
mpi4py                    3.1.4            py39hfc96bbd_0  
mpich                     3.3.2                hc856adb_0  
mpmath                    1.3.0                    pypi_0    pypi
multidict                 6.0.4                    pypi_0    pypi
multiprocess              0.70.14                  pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
nettle                    3.7.3                hbbd107a_1  
networkx                  3.0                      pypi_0    pypi
ninja                     1.11.1                   pypi_0    pypi
numpy                     1.24.2                   pypi_0    pypi
numpy-base                1.23.5           py39h31eccc5_0  
nvidia-cublas-cu11        11.10.3.66               pypi_0    pypi
nvidia-cuda-cupti-cu11    11.7.101                 pypi_0    pypi
nvidia-cuda-nvrtc-cu11    11.7.99                  pypi_0    pypi
nvidia-cuda-runtime-cu11  11.7.99                  pypi_0    pypi
nvidia-cudnn-cu11         8.5.0.96                 pypi_0    pypi
nvidia-cufft-cu11         10.9.0.58                pypi_0    pypi
nvidia-curand-cu11        10.2.10.91               pypi_0    pypi
nvidia-cusolver-cu11      11.4.0.1                 pypi_0    pypi
nvidia-cusparse-cu11      11.7.4.91                pypi_0    pypi
nvidia-nccl-cu11          2.14.3                   pypi_0    pypi
nvidia-nvtx-cu11          11.7.91                  pypi_0    pypi
openh264                  2.1.1                h4ff587b_0  
openssl                   1.1.1t               h7f8727e_0  
packaging                 23.0                     pypi_0    pypi
pandas                    2.0.0                    pypi_0    pypi
pathtools                 0.1.2                    pypi_0    pypi
peft                      0.3.0.dev0               pypi_0    pypi
pillow                    9.4.0            py39h6a678d5_0  
pip                       23.0.1           py39h06a4308_0  
prompt-toolkit            3.0.0                    pypi_0    pypi
protobuf                  3.18.3                   pypi_0    pypi
psutil                    5.9.4                    pypi_0    pypi
py-cpuinfo                9.0.0                    pypi_0    pypi
pyarrow                   11.0.0                   pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0  
pydantic                  1.10.7                   pypi_0    pypi
pyopenssl                 23.0.0           py39h06a4308_0  
pysocks                   1.7.1            py39h06a4308_0  
python                    3.9.16               h7a1cb2a_2  
python-dateutil           2.8.2                    pypi_0    pypi
pytorch                   1.12.0          py3.9_cuda11.3_cudnn8.3.2_0    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2023.3                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
readline                  8.2                  h5eee18b_0  
regex                     2023.3.23                pypi_0    pypi
requests                  2.28.2                   pypi_0    pypi
responses                 0.18.0                   pypi_0    pypi
sentencepiece             0.1.97                   pypi_0    pypi
sentry-sdk                1.19.0                   pypi_0    pypi
setproctitle              1.3.2                    pypi_0    pypi
setuptools                65.6.3           py39h06a4308_0  
six                       1.16.0             pyhd3eb1b0_1  
smmap                     5.0.0                    pypi_0    pypi
sqlite                    3.41.1               h5eee18b_0  
sympy                     1.11.1                   pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
tokenizers                0.13.2                   pypi_0    pypi
torch                     2.0.0                    pypi_0    pypi
torchaudio                0.12.0               py39_cu113    pytorch
torchvision               0.13.0               py39_cu113    pytorch
tqdm                      4.65.0                   pypi_0    pypi
transformers              4.28.0.dev0              pypi_0    pypi
triton                    2.0.0                    pypi_0    pypi
trl                       0.4.2.dev0               pypi_0    pypi
typing-extensions         4.5.0                    pypi_0    pypi
typing_extensions         4.4.0            py39h06a4308_0  
tzdata                    2023.3                   pypi_0    pypi
urllib3                   1.26.15          py39h06a4308_0  
wandb                     0.14.0                   pypi_0    pypi
wcwidth                   0.2.6                    pypi_0    pypi
werkzeug                  2.2.3                    pypi_0    pypi
wheel                     0.38.4           py39h06a4308_0  
xxhash                    3.2.0                    pypi_0    pypi
xz                        5.2.10               h5eee18b_1  
yarl                      1.8.2                    pypi_0    pypi
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0  
zstd                      1.5.4                hc292b87_0

**Comment by shizhediao** [comment]
这环境里好像没有安装lmflow？

--------
There are no lmflow package.

**Comment by LiuMingwu** [comment]
重新安装环境还是这个·问题，报错信息好像就是反复出现这几个函数
![image](https://user-images.githubusercontent.com/37980561/233842965-f1b42fef-0fb7-45b1-9f29-3dfb11501eee.png)

**Comment by shizhediao** [comment]
> 这是我目前conda list，请问是否是环境问题所致？ _libgcc_mutex 0.1 main _openmp_mutex 5.1 1_gnu accelerate 0.18.0 pypi_0 pypi aiohttp 3.8.4 pypi_0 pypi aiosignal 1.3.1 pypi_0 pypi appdirs 1.4.4 pypi_0 pypi async-timeout 4.0.2 pypi_0 pypi attrs 22.2.0 pypi_0 pypi blas 1.0 mkl brotlipy 0.7.0 py39h27cfd23_1003 bzip2 1.0.8 h7b6447c_0 ca-certificates 2023.01.10 h06a4308_0 cchardet 2.1.7 pypi_0 pypi certifi 2022.12.7 py39h06a4308_0 cffi 1.15.1 py39h5eee18b_3 chardet 5.1.0 pypi_0 pypi charset-normalizer 3.1.0 pypi_0 pypi click 8.1.3 pypi_0 pypi cmake 3.26.1 pypi_0 pypi cpm-kernels 1.0.11 pypi_0 pypi cryptography 39.0.1 py39h9ce1e76_0 cudatoolkit 11.3.1 h2bc3f7f_2 datasets 2.10.1 pypi_0 pypi deepspeed 0.8.3 pypi_0 pypi dill 0.3.6 pypi_0 pypi docker-pycreds 0.4.0 pypi_0 pypi ffmpeg 4.3 hf484d3e_0 pytorch filelock 3.10.7 pypi_0 pypi flask 2.2.3 pypi_0 pypi flask-cors 3.0.10 pypi_0 pypi flit-core 3.8.0 py39h06a4308_0 freetype 2.12.1 h4a9f257_0 frozenlist 1.3.3 pypi_0 pypi fsspec 2023.3.0 pypi_0 pypi giflib 5.2.1 h5eee18b_3 gitdb 4.0.10 pypi_0 pypi gitpython 3.1.31 pypi_0 pypi gmp 6.2.1 h295c915_3 gnutls 3.6.15 he1e5248_0 hjson 3.1.0 pypi_0 pypi huggingface-hub 0.13.3 pypi_0 pypi icetk 0.0.7 pypi_0 pypi idna 3.4 py39h06a4308_0 importlib-metadata 6.1.0 pypi_0 pypi intel-openmp 2021.4.0 h06a4308_3561 itsdangerous 2.1.2 pypi_0 pypi jinja2 3.1.2 pypi_0 pypi jpeg 9e h5eee18b_1 lame 3.100 h7b6447c_0 lcms2 2.12 h3be6417_0 ld_impl_linux-64 2.38 h1181459_1 lerc 3.0 h295c915_0 libdeflate 1.17 h5eee18b_0 libffi 3.4.2 h6a678d5_6 libgcc-ng 11.2.0 h1234567_1 libgfortran-ng 7.5.0 ha8ba4b0_17 libgfortran4 7.5.0 ha8ba4b0_17 libgomp 11.2.0 h1234567_1 libiconv 1.16 h7f8727e_2 libidn2 2.3.2 h7f8727e_0 libpng 1.6.39 h5eee18b_0 libstdcxx-ng 11.2.0 h1234567_1 libtasn1 4.16.0 h27cfd23_0 libtiff 4.5.0 h6a678d5_2 libunistring 0.9.10 h27cfd23_0 libwebp 1.2.4 h11a3e52_1 libwebp-base 1.2.4 h5eee18b_1 lit 16.0.0 pypi_0 pypi lz4-c 1.9.4 h6a678d5_0 markupsafe 2.1.2 pypi_0 pypi mkl 2021.4.0 h06a4308_640 mkl-service 2.4.0 py39h7f8727e_0 mkl_fft 1.3.1 py39hd3c417c_0 mkl_random 1.2.2 py39h51133e4_0 mpi 1.0 mpich mpi4py 3.1.4 py39hfc96bbd_0 mpich 3.3.2 hc856adb_0 mpmath 1.3.0 pypi_0 pypi multidict 6.0.4 pypi_0 pypi multiprocess 0.70.14 pypi_0 pypi ncurses 6.4 h6a678d5_0 nettle 3.7.3 hbbd107a_1 networkx 3.0 pypi_0 pypi ninja 1.11.1 pypi_0 pypi numpy 1.24.2 pypi_0 pypi numpy-base 1.23.5 py39h31eccc5_0 nvidia-cublas-cu11 11.10.3.66 pypi_0 pypi nvidia-cuda-cupti-cu11 11.7.101 pypi_0 pypi nvidia-cuda-nvrtc-cu11 11.7.99 pypi_0 pypi nvidia-cuda-runtime-cu11 11.7.99 pypi_0 pypi nvidia-cudnn-cu11 8.5.0.96 pypi_0 pypi nvidia-cufft-cu11 10.9.0.58 pypi_0 pypi nvidia-curand-cu11 10.2.10.91 pypi_0 pypi nvidia-cusolver-cu11 11.4.0.1 pypi_0 pypi nvidia-cusparse-cu11 11.7.4.91 pypi_0 pypi nvidia-nccl-cu11 2.14.3 pypi_0 pypi nvidia-nvtx-cu11 11.7.91 pypi_0 pypi openh264 2.1.1 h4ff587b_0 openssl 1.1.1t h7f8727e_0 packaging 23.0 pypi_0 pypi pandas 2.0.0 pypi_0 pypi pathtools 0.1.2 pypi_0 pypi peft 0.3.0.dev0 pypi_0 pypi pillow 9.4.0 py39h6a678d5_0 pip 23.0.1 py39h06a4308_0 prompt-toolkit 3.0.0 pypi_0 pypi protobuf 3.18.3 pypi_0 pypi psutil 5.9.4 pypi_0 pypi py-cpuinfo 9.0.0 pypi_0 pypi pyarrow 11.0.0 pypi_0 pypi pycparser 2.21 pyhd3eb1b0_0 pydantic 1.10.7 pypi_0 pypi pyopenssl 23.0.0 py39h06a4308_0 pysocks 1.7.1 py39h06a4308_0 python 3.9.16 h7a1cb2a_2 python-dateutil 2.8.2 pypi_0 pypi pytorch 1.12.0 py3.9_cuda11.3_cudnn8.3.2_0 pytorch pytorch-mutex 1.0 cuda pytorch pytz 2023.3 pypi_0 pypi pyyaml 6.0 pypi_0 pypi readline 8.2 h5eee18b_0 regex 2023.3.23 pypi_0 pypi requests 2.28.2 pypi_0 pypi responses 0.18.0 pypi_0 pypi sentencepiece 0.1.97 pypi_0 pypi sentry-sdk 1.19.0 pypi_0 pypi setproctitle 1.3.2 pypi_0 pypi setuptools 65.6.3 py39h06a4308_0 six 1.16.0 pyhd3eb1b0_1 smmap 5.0.0 pypi_0 pypi sqlite 3.41.1 h5eee18b_0 sympy 1.11.1 pypi_0 pypi tk 8.6.12 h1ccaba5_0 tokenizers 0.13.2 pypi_0 pypi torch 2.0.0 pypi_0 pypi torchaudio 0.12.0 py39_cu113 pytorch torchvision 0.13.0 py39_cu113 pytorch tqdm 4.65.0 pypi_0 pypi transformers 4.28.0.dev0 pypi_0 pypi triton 2.0.0 pypi_0 pypi trl 0.4.2.dev0 pypi_0 pypi typing-extensions 4.5.0 pypi_0 pypi typing_extensions 4.4.0 py39h06a4308_0 tzdata 2023.3 pypi_0 pypi urllib3 1.26.15 py39h06a4308_0 wandb 0.14.0 pypi_0 pypi wcwidth 0.2.6 pypi_0 pypi werkzeug 2.2.3 pypi_0 pypi wheel 0.38.4 py39h06a4308_0 xxhash 3.2.0 pypi_0 pypi xz 5.2.10 h5eee18b_1 yarl 1.8.2 pypi_0 pypi zipp 3.15.0 pypi_0 pypi zlib 1.2.13 h5eee18b_0 zstd 1.5.4 hc292b87_0

这个环境里没有看到lmflow安装包，请检查一下是否安装成功。安装成功后会在这个列表里看到lmflow

**Comment by LiuMingwu** [comment]
目前应该重新安装conda env，请问这个问题可能是因为显存导致的吗？
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
appdirs                   1.4.4                    pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
blas                      1.0                         mkl  
brotlipy                  0.7.0           py39h27cfd23_1003  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2023.01.10           h06a4308_0  
certifi                   2022.12.7        py39h06a4308_0  
cffi                      1.15.1           py39h5eee18b_3  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.1.3                    pypi_0    pypi
contourpy                 1.0.7                    pypi_0    pypi
cpm-kernels               1.0.11                   pypi_0    pypi
cryptography              39.0.1           py39h9ce1e76_0  
cudatoolkit               11.3.1               h2bc3f7f_2  
cycler                    0.11.0                   pypi_0    pypi
datasets                  2.10.1                   pypi_0    pypi
deepspeed                 0.8.3                    pypi_0    pypi
dill                      0.3.6                    pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
filelock                  3.12.0                   pypi_0    pypi
flask                     2.2.3                    pypi_0    pypi
flask-cors                3.0.10                   pypi_0    pypi
fonttools                 4.39.3                   pypi_0    pypi
freetype                  2.12.1               h4a9f257_0  
fsspec                    2023.4.0                 pypi_0    pypi
giflib                    5.2.1                h5eee18b_3  
gmp                       6.2.1                h295c915_3  
gnutls                    3.6.15               he1e5248_0  
hjson                     3.1.0                    pypi_0    pypi
icetk                     0.0.7                    pypi_0    pypi
idna                      3.4              py39h06a4308_0  
importlib-metadata        6.6.0                    pypi_0    pypi
importlib-resources       5.12.0                   pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561  
itsdangerous              2.1.2                    pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
jpeg                      9e                   h5eee18b_1  
kiwisolver                1.4.4                    pypi_0    pypi
lame                      3.100                h7b6447c_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.38                 h1181459_1  
lerc                      3.0                  h295c915_0  
libdeflate                1.17                 h5eee18b_0  
libffi                    3.4.2                h6a678d5_6  
libgcc-ng                 11.2.0               h1234567_1  
libgfortran-ng            7.5.0               ha8ba4b0_17  
libgfortran4              7.5.0               ha8ba4b0_17  
libgomp                   11.2.0               h1234567_1  
libiconv                  1.16                 h7f8727e_2  
libidn2                   2.3.2                h7f8727e_0  
libpng                    1.6.39               h5eee18b_0  
libstdcxx-ng              11.2.0               h1234567_1  
libtasn1                  4.19.0               h5eee18b_0  
libtiff                   4.5.0                h6a678d5_2  
libunistring              0.9.10               h27cfd23_0  
libwebp                   1.2.4                h11a3e52_1  
libwebp-base              1.2.4                h5eee18b_1  
lmflow                    0.0.1                     dev_0    <develop>
lz4-c                     1.9.4                h6a678d5_0  
markupsafe                2.1.2                    pypi_0    pypi
matplotlib                3.7.1                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py39h7f8727e_0  
mkl_fft                   1.3.1            py39hd3c417c_0  
mkl_random                1.2.2            py39h51133e4_0  
mpi                       1.0                       mpich  
mpi4py                    3.1.4            py39hfc96bbd_0  
mpich                     3.3.2                hc856adb_0  
mpmath                    1.3.0                    pypi_0    pypi
multiprocess              0.70.14                  pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
nettle                    3.7.3                hbbd107a_1  
networkx                  3.1                      pypi_0    pypi
ninja                     1.11.1                   pypi_0    pypi
numpy                     1.24.2                   pypi_0    pypi
openh264                  2.1.1                h4ff587b_0  
openssl                   1.1.1t               h7f8727e_0  
packaging                 23.1                     pypi_0    pypi
pandas                    2.0.0                    pypi_0    pypi
peft                      0.3.0.dev0               pypi_0    pypi
pillow                    9.4.0            py39h6a678d5_0  
pip                       23.0.1           py39h06a4308_0  
prompt-toolkit            3.0.0                    pypi_0    pypi
protobuf                  3.18.3                   pypi_0    pypi
psutil                    5.9.5                    pypi_0    pypi
py-cpuinfo                9.0.0                    pypi_0    pypi
pyarrow                   11.0.0                   pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0  
pyopenssl                 23.0.0           py39h06a4308_0  
pyparsing                 3.0.9                    pypi_0    pypi
pysocks                   1.7.1            py39h06a4308_0  
python                    3.9.16               h7a1cb2a_2  
python-dateutil           2.8.2                    pypi_0    pypi
pytorch                   1.12.1          py3.9_cuda11.3_cudnn8.3.2_0    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2023.3                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
readline                  8.2                  h5eee18b_0  
regex                     2023.3.23                pypi_0    pypi
requests                  2.28.1           py39h06a4308_1  
responses                 0.18.0                   pypi_0    pypi
setuptools                66.0.0           py39h06a4308_0  
six                       1.16.0             pyhd3eb1b0_1  
sqlite                    3.41.2               h5eee18b_0  
sympy                     1.11.1                   pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
torchaudio                0.12.1               py39_cu113    pytorch
torchvision               0.13.1               py39_cu113    pytorch
tqdm                      4.65.0                   pypi_0    pypi
trl                       0.4.2.dev0               pypi_0    pypi
typing_extensions         4.5.0            py39h06a4308_0  
tzdata                    2023.3                   pypi_0    pypi
urllib3                   1.26.15          py39h06a4308_0  
wandb                     0.14.0                   pypi_0    pypi
wcwidth                   0.2.6                    pypi_0    pypi
werkzeug                  2.2.3                    pypi_0    pypi
wheel                     0.38.4           py39h06a4308_0  
xxhash                    3.2.0                    pypi_0    pypi
xz                        5.2.10               h5eee18b_1  
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0  
zstd                      1.5.5                hc292b87_0

**Comment by shizhediao** [comment]
现在看起来lmflow已经成功安装，请问还是有原来的问题吗？现在显存是多大？

**Comment by LiuMingwu** [comment]
是的，经过重新安装环境，现在已经可以可以运行，但是不清楚之前错误的原因。感谢您的帮助！
