### ISSUE TITLE
Question about fineturn : when i used 3 v100-GPUs to loar finetune a model the machine is out of memory. But 1 v100 GPU is ok. how to fix it?

### ISSUE THREAD

**Issue by 2718564960** [OptimalScale/LMFlow#310]
Question: when i used 3 v100 GPUs to loar finetune a model the machine is out of memory.(load model?) But 1 v100 GPU is ok. 
 I think it used too much memory at the beginning of the load model. When training the model, CPU memory reduced.
If i can't add the CPU memory, how to fix it?
Thank you.
-----------------------
加载的模型是llama-7b-hf， 在用一张卡训练时，一开始内存占用率30%，训练时就会降到1%. 如果3张卡同时训练，cpu内存就不够了。请问有什么办法解决多卡 cpu 内存不足的问题么？

**Comment by shizhediao** [comment]
可以看一下目前使用的deepspeed config，调整不同的zero策略

-------
You can take a look at the currently used deepspeed config and adjust different zero strategies

**Comment by 2718564960** [comment]
> 可以看一下目前使用的deepspeed config，调整不同的zero策略
> 
> You can take a look at the currently used deepspeed config and adjust different zero strategies

ok, thank you.
