### ISSUE TITLE
[API Design]是否支持对量化的模型进行微调训练？

### ISSUE THREAD

**Issue by libigfat** [OptimalScale/LMFlow#412]
开发者您好，由于显存不足，无法对llama 7B完整模型训练，想问下框架是否支持对llama 7B int4量化的模型进行微调训练？

**Comment by shizhediao** [comment]
目前还不支持，我们建议使用bf16进行训练，更加稳定

-----
Currently it is not supported. We recommend using bf16 for training, as it is more stable.

**Comment by libigfat** [comment]
好的，感谢开发者！
