### ISSUE TITLE
[BUG]：pip install -e .  运行这个命令会报错，git config --list并未设置代理

### ISSUE THREAD

**Issue by ShiXiangXiang123** [OptimalScale/LMFlow#434]
fatal: 无法访问 'https://github.com/EleutherAI/lm-evaluation-harness.git/'：GnuTLS recv error (-54): Error in the pull function.
  error: subprocess-exited-with-error
  
  × git fetch -q https://github.com/EleutherAI/lm-evaluation-harness.git e47e01beea79cfe87421e2dac49e64d499c240b4 did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git fetch -q https://github.com/EleutherAI/lm-evaluation-harness.git e47e01beea79cfe87421e2dac49e64d499c240b4 did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by shizhediao** [comment]
应该是网络问题，可以手动将所需要的包下载到本地进行替换

**Comment by JarringBye** [comment]
网络问题，使用'kgithub'镜像网址替换'github'

**Comment by ShiXiangXiang123** [comment]
> 应该是网络问题，可以手动将所需要的包下载到本地进行替换
是的，确实网络问题，我换了就行了。

**Comment by ShiXiangXiang123** [comment]
> 网络问题，使用'kgithub'镜像网址替换'github'

谢谢，换了之后好了。
