### ISSUE TITLE
[BUG]我在跑./scripts/run_finetune.sh的时候报错了，求大佬们帮我这个专科小学生看看问题

### ISSUE THREAD

**Issue by ShiXiangXiang123** [OptimalScale/LMFlow#436]
raise UsageError("api_key not configured (no-tty). call " + directive)
wandb.errors.UsageError: api_key not configured (no-tty). call wandb.login(key=[your_api_key])
[2023-06-01 06:02:11,175] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 10664

**Comment by shizhediao** [comment]
可以在命令行中键入 `wandb offline` 来关闭wandb

**Comment by orderer0001** [comment]
运行wandb offline 返回W&B offline. Running your script from this directory will only write metadata locally. Use wandb disabled to completely turn off W&B. 应该说已经是离线了，但是还是运行不了  上面同样的报错

> 可以在命令行中键入 `wandb offline` 来关闭wandb

**Comment by kwunhang** [comment]
> 运行wandb offline 返回W&B offline. Running your script from this directory will only write metadata locally. Use wandb disabled to completely turn off W&B. 应该说已经是离线了，但是还是运行不了 上面同样的报错
> 
> > 可以在命令行中键入 `wandb offline` 来关闭wandb

Try enter `export WANDB_MODE=disabled` in your terminal before running your program
