### ISSUE TITLE
[BUG]在跑./scripts/run_finetune.sh的时候成功了，但是显示出如下内容，请问这个显示是告诉我什么的

### ISSUE THREAD

**Issue by ShiXiangXiang123** [OptimalScale/LMFlow#437]
![fa7efb0920dbbea1e0b06b9699e6060b](https://github.com/OptimalScale/LMFlow/assets/107922257/2565afef-4e4f-4fcf-b101-f78fa00468de)

**Comment by SHUMKASHUN** [comment]
wandb的实验监控，是正常的
