### ISSUE TITLE
[API Design]开发者您好，一个模型能否切分在多张显卡上进行微调训练？

### ISSUE THREAD

**Issue by libigfat** [OptimalScale/LMFlow#445]
我使用1张Tesla T4(16G)对LLaMA-7B模型进行LoRA微调训练，提示CUDA OOM，显存不足。

可以再增加一张Tesla T4(16G)，使显存达到2*16G=32G，切分LLaMA-7B模型分布在两张显卡上，从而解决显存不足的问题嘛？

**Comment by research4pan** [comment]
Thanks for your interest in LMFlow! Yes, we support multi-GPU training, even multi-node training. You can use `--deepspeed configs/ds_config_zero3.json` and makes all GPUs visible for this program. The program will automatically do model split and model parallelism for you.

**Comment by libigfat** [comment]
感谢，我已经成功使用ds_config_zero3.json在多张显卡上微调训练LLaMA-7B模型！
