### ISSUE TITLE
请问有对chatglm进行自监督成功的例子吗？

### ISSUE THREAD

**Issue by calvinzhan** [OptimalScale/LMFlow#447]
之前问的一个问题的issue：[https://github.com/OptimalScale/LMFlow/issues/296] 已经关掉了，所以重新开一个。

我对chatglm6b进行纯文本的自监督训练。使用了deepspeed + lora的方案，训练集就是一行行的纯文本，输入模型，input和label相同。训练出来得到一个lora的adapter模型。再用LoraModel的merge_and_unload进行融合，得到微调后的融合模型

预测时，用load_checkpoint_and_dispatch()分布式载入模型（因为单GPU显存不够）。发现已经只能回答抱歉，我不理解之类的语句了。不知你们有经过指令微调后的LLM，再进行纯文本自监督训练成功的例子吗？我在其它对chatglm微调的repo里，还没发现有自监督的例子，所以很希望从你们这里能学习到这样的技术。

**Comment by research4pan** [comment]
Thanks for your interest in LMFlow! Our robin-7b can be viewed as self-supervised learning, which achieves competitive performance on chitchat. You can find the data and released model in [this section of README](https://github.com/OptimalScale/LMFlow#latest-news). Thanks 😄

**Comment by calvinzhan** [comment]
Did I get your points: robin-7b was trained from LLaMA-7B with [LMFlow-data](http://lmflow.org:5000/lmflow_data.tar.gz) only as training data?

**Comment by research4pan** [comment]
Yes, llama-7b + LMFlow-data ----- finetuning------> robin-7b.

**Comment by calvinzhan** [comment]
LMFlow-data like  "text": "###Human: 写一篇关于人工智能与未来生活的文章。\n###Assistant:\n人工智能（AI）在当今世界中正在迅速发展，并已经影响到我们日常生活的各个方面。未来，AI将继续发挥重要作用，尤其是在以下领域：医疗保健、教育、制造业等。人工智能的应用也将深入到现在未涉及的新领域中。\n###Human: 提取一下文章最重要的观点。\n###Assistant:人工智能在未来生活中预计将发挥更加重要的作用。AI将会推动医疗保健、教育、制造业等领域的进步，它也将迅速渗透到新兴领域。" is in pure text format, but I wouldn't treat it as naturally pure text. You have to construct it manually which can't be got  easily in different domains.

I would like to know if we can still train llm on domains when the text is like "截至2016年底,新疆油田公司克拉玛依电厂先后实施了热电联供和燃气轮机低氮燃烧改造项目——热电联供项目替代白碱滩区燃煤供热车间7个,关停燃煤锅炉33台,二氧化硫、烟尘、氮氧化物等污染物年排放量减少1 900 t".

By my test on chatglm, seems it has lost the conversation ability.

**Comment by calvinzhan** [comment]
Anyone succeeded in the above scenario before?

**Comment by shizhediao** [comment]
Hi,
We suggest trying LLaMA-7b first, which is good in our experiments.
Thanks!
