### ISSUE TITLE
[BUG]运行./scripts/run_chatbot.sh 报了如下错误

### ISSUE THREAD

**Issue by ShiXiangXiang123** [OptimalScale/LMFlow#448]
![f05408dddac1d376aa0ea0dab0e298c2](https://github.com/OptimalScale/LMFlow/assets/107922257/20da48e9-8df5-41d9-be82-74cdc7ca795d)

**Comment by ShiXiangXiang123** [comment]
我自己修改了，嘿嘿。应该是参数名字重复问题吧？非常感谢你们的坚持！很感谢很感谢，也希望能够在上面多帮帮我们，嘻嘻。那个可以告诉我这个新手output_models里面的模型要用什么显卡才能带的动吗？

**Comment by research4pan** [comment]
You are welcome 😄 Regarding finetuning, 7b models normally requires 24G GPU memory, thus RTX 3090 should suffice. For larger models, e.g. 13b, multiple GPUs with model parallelism is needed. As for inference, normally the GPU memory consumption is less than finetuning. 16G GPU memory should be finetune for inferencing 7b, and 11G GPU can handle 3b models, as demonstrated in our [colab example](https://colab.research.google.com/drive/1P9Hf6_mLE7WHH92pw73j9D5kz6GTdkow?usp=sharing). Hope that answers your question.

客气～ 😄 微调的话，7b模型一般24G的显存就可以，比如单卡RTX 3090显卡。大一点的模型，比如13b，需要多卡或更大显存的显卡。推理的话，正常情况显存消耗比微调要少。16G显存应该就能推得动7b，11G显存就可以推理3b模型（可以参考我们的[colab例子](https://colab.research.google.com/drive/1P9Hf6_mLE7WHH92pw73j9D5kz6GTdkow?usp=sharing)。希望能对您有所帮助。
