### ISSUE TITLE
Robin-7b-v2 运行后 回复乱码

### ISSUE THREAD

**Issue by abc20220327** [OptimalScale/LMFlow#455]
![image](https://github.com/OptimalScale/LMFlow/assets/102452590/3b9d597b-c3d7-4c2c-b218-bcc656403291)

**Comment by shizhediao** [comment]
多谢关注，可以贴一下全部的运行指令吗？

--------------
Can you provide the exact command you are running? Thanks

**Comment by research4pan** [comment]
It is highly possible that the provided model diff hasn't been merge with the original model. In that case, you may refer to [this section of README](https://github.com/OptimalScale/LMFlow#53-reproduce-the-result). Thanks 😄
