### ISSUE TITLE
[BUG]普通用户运行./scripts/run_finetune.sh 总是出现如下问题，但是我当我把anconda都放在超级用户下就不会出现这个问题，但是那样不好，请问普通用户在那么解决这个问题？

### ISSUE THREAD

**Issue by ShiXiangXiang123** [OptimalScale/LMFlow#457]
![image](https://github.com/OptimalScale/LMFlow/assets/107922257/73d1e918-bb1c-4323-9520-8f6f2621c589)

**Comment by ShiXiangXiang123** [comment]
解决了！！！！！

**Comment by shizhediao** [comment]
恭喜恭喜！我先把这个issue关掉，后面有问题欢迎开一个新的issue
