### ISSUE TITLE
run examples/chatbot.py  model ask himself and answer

### ISSUE THREAD

**Issue by Shelton1013** [OptimalScale/LMFlow#458]
<img width="633" alt="fc7227bf4cd618cc36c9fd054222951" src="https://github.com/OptimalScale/LMFlow/assets/123912248/a0698eb0-1ba4-4888-84dc-b68012952769">
</br>
I run examples/chatbot.py with finetuned llama7b</br>
The content in the red box is what I actually asked</br>
The content in the blue box is what model asked himself</br>

**Comment by ShiXiangXiang123** [comment]
微调的 llama7b，请问需要什么显卡，跑多久可以ok?

**Comment by shizhediao** [comment]
推荐使用3090或更好的显卡。5w数据量大概需要5小时

**Comment by Shelton1013** [comment]
> 推荐使用3090或更好的显卡。5w数据量大概需要5小时

May I ask what's the reason for the stiuation appear in the image above</br>
chatbot answer my input questionI(red box), then ask himself a new question(blue box).</br>

**Comment by Shelton1013** [comment]
> 微调的 llama7b，请问需要什么显卡，跑多久可以ok?

单卡A100, 1w条数据跑了6小时

**Comment by Shelton1013** [comment]
> 推荐使用3090或更好的显卡。5w数据量大概需要5小时

请问我上面图片中，模型自问自答的情况是什么原因。我先提出了一个问题，模型回答以后，又自己提出了一个问题并且回答。

**Comment by shizhediao** [comment]
建议使用###分隔符以及full model training
-----
We'll suggest using `###` as the separator and full model training.

**Comment by Shelton1013** [comment]
> 建议使用###分隔符以及full model training
> 
> We'll suggest using `###` as the separator and full model training.

感谢，我通过full model training解决了这个问题
