### ISSUE TITLE
[BUG] 我想替换run_chatbot_chatglm.sh中的模型，替换成llama7b-lora-medical，应该怎么运行，参数怎么写

### ISSUE THREAD

**Issue by ShiXiangXiang123** [OptimalScale/LMFlow#461]
![92e02d26175500b995975a42a755119d](https://github.com/OptimalScale/LMFlow/assets/107922257/5465ed3f-b53c-4211-a329-f0d2ae7eaac7)
![af54a1c5a9eda375d76ae5d8b496340b](https://github.com/OptimalScale/LMFlow/assets/107922257/bf1e7882-a28f-43cc-a6c7-bd138f8f1f06)

**Comment by ShiXiangXiang123** [comment]
> 
./scripts/run_chatbot.sh {这里面可以填写output_models里面的模型吗?还是说填写其他文件夹里的模型？还是说自己去HF上下载}
有没有运行的代码供参考，我想我应该没搞明白怎么去调用，我非常渴望弄懂，希望可以得到您的帮忙。

**Comment by shizhediao** [comment]
可以填写模型的名称或者路径，HF的名称也可以直接填写，代码会自动下载HF的名称。
注意填写的模型要是完整的模型，如果下载的模型是delta 权重，需要先和主模型进行merge
