### ISSUE TITLE
如何修改workflow以基于BLOOM（例如BLOOM_560M）模型，进行整套的finetune以及RAFT alignment、evaluate等？

### ISSUE THREAD

**Issue by tonymhl** [OptimalScale/LMFlow#463]
是否只需修改参数，如：
deepspeed ${deepspeed_args} \
  examples/finetune.py \
    --model_name_or_path Bloom_560m \
    --dataset_path ${dataset_path} \
    --output_dir ${output_dir} --overwrite_output_dir \
    --num_train_epochs 0.01 \
    --learning_rate 2e-5 \
    --block_size 512 \
    --per_device_train_batch_size 1 \
    --deepspeed configs/ds_config_zero3.json \
    --bf16 \
    --run_name finetune \
    --validation_split_percentage 0 \
    --logging_steps 20 \
    --do_train \
    --ddp_timeout 72000 \
    --save_steps 5000 \
    --dataloader_num_workers 1 \
    | tee ${log_dir}/train.log \
    2> ${log_dir}/train.err
    
    如何查看支持的模型种类及其对应的参数？

**Comment by tonymhl** [comment]
地址好像是：
--model_name_or_path bigscience/bloom-560m

**Comment by shizhediao** [comment]
如果想修改模型，通过修改`model_name_or_path` 即可完成。
谢谢
