### ISSUE TITLE
Unable to resovle any data

### ISSUE THREAD

**Issue by ShiXiangXiang123** [OptimalScale/LMFlow#468]
![05a46ac66246a9dcba6e70b8fd535190](https://github.com/OptimalScale/LMFlow/assets/107922257/b3584419-f62e-4b00-ac86-06980718e6c9)
![ce50e482af0d09a287c794d8e35769ff](https://github.com/OptimalScale/LMFlow/assets/107922257/79cd665e-8fd5-4b74-bdf3-aee5e9dbd42b)

**Comment by tonymhl** [comment]
--datasetpath data/example_dataset/train
👍

**Comment by ShiXiangXiang123** [comment]
> I think it is **LMFlow/data/example_dataset/train/train_50.json** rather than LMFlow/data/example_dataset/train_50.json

非常感谢你的纠正。
