### ISSUE TITLE
[BUG]运行examples/finetune.py  报错了  求大佬帮忙看看

### ISSUE THREAD

**Issue by ShiXiangXiang123** [OptimalScale/LMFlow#469]
![3abf44b1105ebc5d3f099bd5cddc3b9e](https://github.com/OptimalScale/LMFlow/assets/107922257/1b37ad23-ce79-4e5e-a783-546c6aefb7c9)

**Comment by shizhediao** [comment]
这个可能和内存不够有关系，参见https://github.com/OptimalScale/LMFlow/issues/179
可以监测一下内存的占用。

**Comment by ShiXiangXiang123** [comment]
> 这个可能和内存不够有关系，参见#179 可以监测一下内存的占用。

感谢
