### ISSUE TITLE
关于训练集和验证集形式的疑问

### ISSUE THREAD

**Issue by abc20220327** [OptimalScale/LMFlow#478]
我在lmflow的例子里看到了几种训练集形式：

1. wiki类的直接放文本的textonly形式，验证集 也是 textonly 数据
2. textonly文本中放的是选择题及 选择题的答案 ，一般验证集 是 text2text
3. textonly文本中放的是判断题及 判断题的答案 ，一般验证集是 text2text
4. text2text的问答，问题和答案都是文本，验证集 也是 text2text问答

我这里想问，以上集中训练集一般都用在什么场景下，或者说都可以用，哪个方案最优吗，

另外我看到 LMFLOW官方 例子说 的 PubMedQA 这类的都是 第2 种形式，这种形式 在 验证时可以选择 --metric accuracy，可以精准进行评分，这样更好的判断训练的结果， 那如果我选择的是 第4中形式，我就没法使用 --metric accuracy进行评分，我目前看到的是 可以用 neg_log_likelihood 进行 判断，但是实际上，回答也是文本，验证集也是文本时，这个结果高未必就代表 实际上 效果好。

以上是我的一些理解，不知道是否对，如果不对请指出。

我还有一个疑问就是： 是不是 即使我拥有的是 第4种类型的数据，我转换为 2,3 这两种类型，更容易让模型学习，也更容易评估，还是说他们场景不同，无法替换，麻烦给予解惑，非常感谢

**Comment by HuihuiChyan** [comment]
预训练阶段一般用textonly，指令微调阶段一般使用text2text。

**Comment by shizhediao** [comment]
Thanks for your reply!
