### ISSUE TITLE
金融智能客服所用的训练数据

### ISSUE THREAD

**Issue by tonymhl** [OptimalScale/LMFlow#479]
Hi
我看了您做的视频分享，【低成本微调垂直领域专属 ChatGPT】 【精准空降到 07:21】 https://www.bilibili.com/video/BV1Pz4y1q7yA/?share_source=copy_web&vd_source=72881a433f18cfcd8d74b29267a8814e&t=441
您提到了训练一个金融场景的智能客服，想了解一下这个场景您所用的数据资料，或者能参考的一些数据资源，因为我也想实践一下这个应用方向，感谢🙏

**Comment by tonymhl** [comment]
感谢回复！我们现在也是比较关注金融投顾场景的问答，这一场景强调了高标准的合规性和无害性，目前还不是很明确要怎么样去很好地实现这种严格标准，不知道您是否能推荐一些相关的 paper 或开源资料？万分感谢！
—————————————————————————————————————————————————————————————————
Thank you for your reply! We are also focusing on the auto Q&A agent in the financial investment advisory scenario, which emphasizes high standards of compliance and harmlessness. Currently, it is not clear how to effectively implement these strict standards. Can you recommend some relevant papers or open source materials? Thank you very much!

**Comment by shizhediao** [comment]
Hi, 关于您提到的这种细分场景，我们确实给不出特别具体的意见和建议。目前学术上的探究应该集中于学术数据集上的验证，距离真实场景的严格标准应该还有一定距离。谢谢！

---------
Hi，Regarding the specific scenario you mentioned, we cannot provide particularly specific opinions and suggestions. Currently, academic research should focus on validating academic datasets, and there should still be a certain distance from the strict standards of real-world scenarios. Thanks!
