### ISSUE TITLE
strange response

### ISSUE THREAD

**Issue by klykq111** [OptimalScale/LMFlow#491]
模型权重是在 https://huggingface.co/LMFlow/Robin-7b-v2/tree/main 下载的，应该不需要再合并了。
启动命令使用的是：
CUDA_VISIBLE_DEVICES=0 python examples/chatbot.py --model_name_or_path /home/gpt/weights/Robin-7b-v2 --deepspeed configs/ds_config_chatbot.json --use_ram_optimized_load False
![2023-06-12_18-49](https://github.com/OptimalScale/LMFlow/assets/42060953/cf14722e-a966-49fb-84af-9e52ac715833)

**Comment by klykq111** [comment]
我使用llama-7b-hf与Robin-7b-v2合并之后，模型输出不乱码了，但是在接着我的续写，自问自答，这是怎么回事：
![image](https://github.com/OptimalScale/LMFlow/assets/42060953/5b3c2c18-1d55-4e7a-bff5-f7320b67a86b)

**Comment by 2033329616** [comment]
怎么合并模型？是用fastchat的apply_delta吗？我使用0.2.17版本的fastchat合并hugging face上的llama-7b模型和lmflow中提供的7B的delta模型后，输出还是有问题

**Comment by klykq111** [comment]
我记得没错的话，我是用的LMFlow提供的代码合并的模型。

```
python utils/apply_delta.py \
    --base-model-path {huggingface-model-name-or-path-to-base-model} \
    --delta-path {path-to-delta-model} \
    --target-model-path {path-to-merged-model}
```

**Comment by shizhediao** [comment]
> 我记得没错的话，我是用的LMFlow提供的代码合并的模型。
> 
> ```
> python utils/apply_delta.py \
>     --base-model-path {huggingface-model-name-or-path-to-base-model} \
>     --delta-path {path-to-delta-model} \
>     --target-model-path {path-to-merged-model}
> ```

请参考这个，谢谢

----

Please refer to this, thanks!

**Comment by 2033329616** [comment]
可以了，谢谢
