### ISSUE TITLE
repeat the question

### ISSUE THREAD

**Issue by Shelton1013** [OptimalScale/LMFlow#492]
使用的模型是llama7b，数据集是用的hugging face上的finance_alpaca（68.9K），制作成了下面的格式：
{
 "type": "text2text",
 "instances": [
  {
   "input": "###Instruction: If you are a financial adviser, customer will ask you some questions. ###Human: For a car, what scams can be plotted with 0% financing vs rebate? ###Chatbot:",
   "output": "The car deal makes money 3 ways. If you pay in one lump payment. If the payment is greater than what they paid for the car, plus their expenses, they make a profit. They loan you the money. You make payments over months or years, if the total amount you pay is greater than what they paid for the car, plus their expenses, plus their finance expenses they make money. Of course the money takes years to come in, or they sell your loan to another business to get the money faster but in a smaller amount. You trade in a car and they sell it at a profit. Of course that new transaction could be a lump sum or a loan on the used car... They or course make money if you bring the car back for maintenance, or you buy lots of expensive dealer options. Some dealers wave two deals in front of you: get a 0% interest loan. These tend to be shorter 12 months vs 36,48,60 or even 72 months. The shorter length makes it harder for many to afford. If you can't swing the 12 large payments they offer you at x% loan for y years that keeps the payments in your budget. pay cash and get a rebate. If you take the rebate you can't get the 0% loan. If you take the 0% loan you can't get the rebate. The price you negotiate minus the rebate is enough to make a profit. The key is not letting them know which offer you are interested in. Don't even mention a trade in until the price of the new car has been finalized. Otherwise they will adjust the price, rebate, interest rate, length of loan,  and trade-in value to maximize their profit. The suggestion of running the numbers through a spreadsheet is a good one. If you get a loan for 2% from your bank/credit union for 3 years and the rebate from the dealer, it will cost less in total than the 0% loan from the dealer. The key is to get the loan approved by the bank/credit union before meeting with the dealer. The money from the bank looks like cash to the dealer..###"
  },
  {
   "input": "###Instruction: If you are a financial adviser, customer will ask you some questions. ###Human: Why does it matter if a Central Bank has a negative rather than 0% interest rate? ###Chatbot:",
   "output": "That is kind of the point, one of the hopes is that it incentivizes banks to stop storing money and start injecting it into the economy themselves. Compared to the European Central Bank investing directly into the economy the way the US central bank has been doing. (The Federal Reserve buying mortgage backed securities) On a country level, individual European countries have tried this before in recent times with no noticeable effect..###"
  }
}

微调的指令如下：
python examples/finetune.py --deepspeed configs/ds_config_zero3.json --use_lora 1 --lor            a_r 8 --save_aggregated_lora 0 --bf16 --run_name finetune_with_lora --model_name_or_path pinkmanlove/            llama-7b-hf  --num_train_epochs 5 --learning_rate 1e-4 --dataset_path /UNICOMFS/yt_ust_makchen_1/LMFl            ow/data/shelton_data --per_device_train_batch_size 1 --per_device_eval_batch_size 1 --validation_spli            t_percentage 0 --logging_steps 20 --block_size 512 --do_train --output_dir output_models/finetune_lla            ma/2023_6_11_finance --overwrite_output_dir --ddp_timeout 72000 --save_steps 5000 --dataloader_num_wo            rkers 1 --use_ram_optimized_load 0

微调后对lora和llama7b进行了merge整合如下：
python examples/merge_lora.py --model_name_or_path pinkmanlove/llama-7b-hf --lora_model_path /UNICOMFS/yt_ust_makchen_1/LMFlow/output_models/finetune_llama/2023_6_11_finance --output_model_path /UNICOMFS/yt_ust_makchen_1/LMFlow/output_models/merged/2023_6_11_finance

测试的指令如下：
python examples/chatbot.py --deepspeed configs/ds_config_chatbot.json --model_name_or_path /UNICOMFS/yt_ust_makchen_1/LMFlow/output_models/merged/2023_6_11_finance --max_new_tokens 100 --prompt_structure "###Instruction: If you are a financial adviser, customer will ask you some questions. ###Human:{input_text}###Chatbot:" --end_string "#"
<img width="703" alt="f440816aa25d7bc123a9d88316b442f" src="https://github.com/OptimalScale/LMFlow/assets/123912248/47f733db-2b2a-461d-8246-391d6421c0f0">

模型只会重复我提出的问题，我更换数据集（中文/英文）都尝试，但仍然只会重复我的问题

**Comment by shizhediao** [comment]
检查一下数据流，在训练的时候input和output是否符合预期。
也可以试一下full model training，不过lora也不会导致重复问题

-----
Please check the data flow to ensure that the input and output are as expected during training. You can also try full model training, but LoRa will not cause duplication issues.

**Comment by Shelton1013** [comment]
> 检查一下数据流，在训练的时候input和output是否符合预期。 也可以试一下full model training，不过lora也不会导致重复问题
> 
> Please check the data flow to ensure that the input and output are as expected during training. You can also try full model training, but LoRa will not cause duplication issues.

使用full model training就没有这个问题了。
还想请教您一个问题，我目前full model training数据量是500条数据，微调效果还比较好，使用的是学习率是2e-5。如果是是5w条或者是更多的数据量，请问学习率设置多少比较合适，或者是否还有其他超参需要对应修改，上面的68.9k的数据集学习的效果就比较差，模型完全没有学到对应的内容, 感觉是我超参设置不合理导致的。
以及数据集中数据的分布差异比较大，是否也会对模型微调的表现有影响

**Comment by shizhediao** [comment]
建议进行实验来确定最佳超参数。
不是很清楚这里提到的“分布差异比较大”具体是有多大，不过可以进行实验看效果。

**Comment by s1ghhh** [comment]
如果你的可调参数比较少（lora的rank比较小或lora的target_modules比较少），finetune大数据集时可能会出现这种情况。加大lora_rank试试。
