### ISSUE TITLE
text_only的文本长度有限制吗？

### ISSUE THREAD

**Issue by equationdz** [OptimalScale/LMFlow#496]
text_only的文本长度有限制吗？
{
  "type": "text_only",
  "instances": [
    {
      "text": "这里的输入文本有长度限制吗？是不是关联性高的上下文都可以放在同一行忽略长度限制？比如一篇新闻稿？"
    },
    ...
  ]
}

**Comment by equationdz** [comment]
顺便问一下text2text是否也存在长度限制，大概是多少？

**Comment by ShiXiangXiang123** [comment]
有的，我今天也遇到这个问题，哥们加联系方式一起讨论

**Comment by shizhediao** [comment]
长度限制受制于模型的位置编码，比如llama 一般是2048.

-----
The length limit is constrained by the positional encoding of the model, such as 2048 for llama.
