### ISSUE TITLE
CUDA cannot be found

### ISSUE THREAD

**Issue by ShiXiangXiang123** [OptimalScale/LMFlow#505]
![P13@Q5EK_RPNCNEZJ`Q%B`1](https://github.com/OptimalScale/LMFlow/assets/107922257/945ab5a6-0c05-4c8d-8c72-c47468dd950b)
![Z 7BVJ~9{A5 SWS)M}U8F6](https://github.com/OptimalScale/LMFlow/assets/107922257/236ffbb2-c7cb-4ee4-8bda-7e112d05f80f)
![{LPGGGJU`}8~7XPC0VFD}UN](https://github.com/OptimalScale/LMFlow/assets/107922257/d88896c4-7cae-43ca-9799-3b5711efb7ca)
![image](https://github.com/OptimalScale/LMFlow/assets/107922257/babcf307-8599-4d4f-bcd1-5c34a05c8e40)

**Comment by shizhediao** [comment]
It seems that there are some problems with your device. Could you try to seek help from your administrator?
Thanks!
