### ISSUE TITLE
'gbk' codec can't decode byte 0xae in position 728: illegal multibyte sequence

### ISSUE THREAD

**Issue by natsukawa520** [OptimalScale/LMFlow#51]
readme_contents = fp.read().strip()
      UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 728: illegal multibyte sequence
在pip install -e . 这一步中

**Comment by research4pan** [comment]
Hi, thanks for your attention! Could you please provide the type of operating systems, e.g. Windows 10, Ubuntu 22.04, along with other settings? Thanks!
感谢您关注LMFlow！请问您方便提供一下操作系统的类型，比如Windows 10/Ubuntu 22.04，以及其他可能相关的系统配置吗？谢谢～

**Comment by natsukawa520** [comment]
> Hi, thanks for your attention! Could you please provide the type of operating systems, e.g. Windows 10, Ubuntu 22.04, along with other settings? Thanks! 感谢您关注LMFlow！请问您方便提供一下操作系统的类型，比如Windows 10/Ubuntu 22.04，以及其他可能相关的系统配置吗？谢谢～

我使用的是Windows 11的操作系统,其他配置均根据文中来一步一步走的 我尝试在上文中open函数里加入encoding='utf-8'的操作,但是遇到了如下的超时的报错.
  fatal: unable to access 'https://github.com/huggingface/peft/': OpenSSL SSL_read: Connection was reset, errno 10054
  fatal: unable to access 'https://github.com/huggingface/peft/': Failed to connect to github.com port 443 after 21066 ms: Timed out
  error: unable to read sha1 file of .github/workflows/build_documentation.yml (9e58cb8a274a1c0425ec159715dc4def076da80f)
  fatal: unable to access 'https://github.com/huggingface/peft/': Failed to connect to github.com port 443 after 21053 ms: Timed out

**Comment by research4pan** [comment]
Thanks for your feedback! Currently our support for Windows platform has not been fully tested yet. Our package is mainly supported in Linux platforms, hence it is possible to encounter unexpected errors.

The good news is, the current problem may not be related to operating systems. According to the error message, it is mainly caused by issues related to accessing git. You can try to change your host and manually install the required python package.

您好，感谢您的反馈！我们目前对Windows平台的支持还没有完全测试，主要是在Linux平台上支持，所以的确可能出现意想不到的问题。不过目前遇到的这个问题可能和Windows无关，主要是无法访问git的问题。您可以尝试科学上网，并按照`requirements.txt`里的依赖配置
```
peft @ git+https://github.com/huggingface/peft@df0e1fb
```
手动clone该代码库并安装：
```
git clone https://github.com/huggingface/peft
cd peft
git checkout df0e1fb
pip install -e .
```
感谢您的反馈！

**Comment by natsukawa520** [comment]
> 

您好,感谢您的回答! 我手动修改了git的代理端口解决了这个问题,但是我在"pip install -e ."这一步的时候安装到deepspeed包的时候出现了以下的问题,即使我给了系统管理员权限仍然无法解决,我手动也没有找到出现错误的具体文件,我目前找不到什么有效的办法解决这一步.
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      系统找不到指定的文件。
      系统找不到指定的文件。
      系统找不到指定的文件。
      系统找不到指定的文件。
      fatal: not a git repository (or any of the parent directories): .git
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\79428\AppData\Local\Temp\pip-install-83l_xj9j\deepspeed_4a3ad7eff86c4cacadbd8e8a59244dd3\setup.py", line 198, in <module>
          create_dir_symlink('..\\..\\csrc', '.\\deepspeed\\ops\\csrc')
        File "C:\Users\79428\AppData\Local\Temp\pip-install-83l_xj9j\deepspeed_4a3ad7eff86c4cacadbd8e8a59244dd3\setup.py", line 190, in create_dir_symlink
          os.remove(dest)
      PermissionError: [WinError 5] 拒绝访问。: '.\\deepspeed\\ops\\csrc'

**Comment by a5225662** [comment]
这个问题在我的机器上解决了，

#### README.MD decode error
(lmflow) D:\LMFlow>pip install -e .
Obtaining file:///D:/LMFlow
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "D:\LMFlow\setup.py", line 24, in <module>
          readme_contents = fp.read().strip()
      UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 728: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```python
 # with open(readme_path,) as fp:
   with open(readme_path,encoding='utf-8') as fp:
```
