### ISSUE TITLE
Support for QLORA

### ISSUE THREAD

**Issue by louisoutin** [OptimalScale/LMFlow#514]
Hello,
Can we finetune model using qlora with LMFlow? (Cf: https://github.com/artidoro/qlora)
Thanks

**Comment by research4pan** [comment]
Thanks for your interest in LMFlow! Currently we haven't supported qlora yet, but it is in our schedule. By the way, we encourage any contributions to accelerate the develop progress. Thanks very much 😄

**Comment by louisoutin** [comment]
Sorry, i've been offline the last week.
I'll try to have a look for QLORA integration, but i need to check more LMFlow codebase first (i'm new to it).
If anyone want to help in this effort, I think we can take example on that PR, should be something pretty similar: https://github.com/tloen/alpaca-lora/pull/487/files

**Comment by shizhediao** [comment]
Hi, thanks.
Agree. I feel that we can do very similar modifications to our code.
If you have any questions about our repo and need help, feel free to let us know.

**Comment by NLPpupil** [comment]
interested in this work, 资瓷。

**Comment by ankitpasi** [comment]
I have created a PR for support for QLoRA (Added QLoRA support for Decoder transformers with tune_strategy "Normal" #613)

Once it is reviewed hopefully it get's merged.

**Comment by shizhediao** [comment]
It has been merged a few weeks ago. Thanks for @ankitpasi 's contribution!
