### ISSUE TITLE
'utf-8' codec can't decode byte 0xb0 in position 45: invalid start byte[BUG]

### ISSUE THREAD

**Issue by LAKan233** [OptimalScale/LMFlow#518]
你好，我尝试运行RAFT的demo时，在运行run_raft_align.sh时，出现了上述的问题，我并没有对数据集以及地址进行任何的改动，请问这个问题的原因是什么呢？

**Comment by shizhediao** [comment]
请问数据集用的什么格式，可否检查一下数据集下载是否正常和完整。
可否分享一下你使用的数据集？

**Comment by LAKan233** [comment]
你好，这个问题我已经解决了，是因为修改路径的时候少打了一个 / 导致的
