### ISSUE TITLE
Message: File not found.

### ISSUE THREAD

**Issue by george66s** [OptimalScale/LMFlow#52]
Hi team,

Thanks for the great work!

Just an issue when downloading the data. Everything else is OK except when downloading 144.214.54.164:5000/natural-instructions.tar.gz, which returns error messages below:

Error response
Error code: 404

Message: File not found.

Error code explanation: HTTPStatus.NOT_FOUND - Nothing matches the given URI.

Could you please help check out?

Lots of thanks!
George

**Comment by research4pan** [comment]
Hi, currently this data is not provided yet. We will update it today. Thanks for your understanding! 😃

**Comment by shizhediao** [comment]
Dear George,
We have put the missing file `natural-instructions.tar.gz` to the right location.
Please try it again.

Thank you!

**Comment by george66s** [comment]
A lot of thanks!
