### ISSUE TITLE
The link to join Slack is broken.

### ISSUE THREAD

**Issue by dsdanielpark** [OptimalScale/LMFlow#525]
The link to join Slack in the readme is broken. It would be great if you could fix it for the purpose of discussing lightweight improvements or for communication related to LMflow. Alternatively, it might be a good idea to consolidate the communication channels into one.

**Comment by shizhediao** [comment]
Hi Thanks for your suggestion!
We have updated a new link: https://join.slack.com/t/lmflow/shared_invite/zt-1wju9nicy-woXbNtS~5MavHSAtiMxmxQ
Thanks!
