### ISSUE TITLE
when running chatbot.py it returns 'InferencerArguments' object has no attribute 'max_new_tokens'

### ISSUE THREAD

**Issue by showgood880702** [OptimalScale/LMFlow#526]
I would like to try to deploy the Robin 7b model on the local machine. I downloaded the robin-7b_v2 model from hugging face and merged it with LLaMa 7b base model using apply_delta.py. when I run the chatbot.py, it seems to work well, but when I input something, it returns an error  'InferencerArguments' object has no attribute 'max_new_tokens'. Or is there any other method to deploy the robin model on the local machine? Thank you very much.

CUDA_VISIBLE_DEVICES=0 python ./examples/chatbot.py --deepspeed configs/ds_config_chatbot.json --model_name_or_path /home/qishi/Projects/LMFlow/output_dir/robin-7b_v2_merged --prompt_structure "A chat between a curious human and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the human's questions.###Human: {input_text}###Assistant:"       --end_string "#"  --use_ram_optimized_load False

User >>> hello
Bot: ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/Projects/LMFlow/./examples/chatbot.py:155 in <module>                                │
│                                                                                                  │
│   152                                                                                            │
│   153                                                                                            │
│   154 if __name__ == "__main__":                                                                 │
│ ❱ 155 │   main()                                                                                 │
│   156                                                                                            │
│                                                                                                  │
│ /home/Projects/LMFlow/./examples/chatbot.py:129 in main                                         │
│                                                                                                  │
│   126 │   │   for response, flag_break in inferencer.stream_inference(                           │
│   127 │   │   │   context=context,                                                               │
│   128 │   │   │   model=model,                                                                   │
│ ❱ 129 │   │   │   max_new_tokens=inferencer_args.max_new_tokens,                                 │
│   130 │   │   │   token_per_step=token_per_step,                                                 │
│   131 │   │   │   temperature=inferencer_args.temperature,                                       │
│   132 │   │   │   end_string=end_string,                                                         │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'InferencerArguments' object has no attribute 'max_new_tokens'

**Comment by research4pan** [comment]
Thanks for your interest in LMFlow! `max_new_tokens` is an argument of inferencer, which is defined [here](https://github.com/OptimalScale/LMFlow/blob/main/src/lmflow/args.py#L592). As the default value is provided in its definition, such error should not occur normally. One possible cause of this error is code version. Could you please try update the main branch and see if the error occur again? Thanks!

**Comment by shizhediao** [comment]
Hi, if it is not working after updating the code by `git pull`, please try `pip install -e .` again.

**Comment by lewislovelock** [comment]
i have the same error  on running ./scripts/run_chatbot.sh
```
AttributeError: 'InferencerArguments' object has no attribute 'max_new_tokens'
```

the command is 
```
./scripts/run_chatbot.sh {output_model_path}
```

**Comment by shizhediao** [comment]
Could you run `git pull` and try it again?
Thank you

**Comment by lewislovelock** [comment]
> Could you run `git pull` and try it again?
> 
> Thank you

I find it was the docker container problem lol.
Thank you!
