### ISSUE TITLE
Host checkpoint file at huggingface for faster download

### ISSUE THREAD

**Issue by pckennethma** [OptimalScale/LMFlow#53]
Hi,

The current download speed of the checkpoint file is a bit slow (~ 1MB/sec.). Could you consider host the checkpoint file at huggingface? Thank you!

**Comment by shizhediao** [comment]
Hi,
Thanks for your great suggestion! We will upload the checkpoints to huggingface hub by tomorrow.
Thank you again!

**Comment by shizhediao** [comment]
Hi,
Thanks for your suggestion! We have uploaded the GPT-based checkpoints to the huggingface hub. The llama checkpoints are mostly LoRAs which are smaller than 30MB so we did not upload them yet.
Please take a look, and you may use them by simply calling:

```
OptimalScale/gpt2-inst-tuning
OptimalScale/gpt2-large-inst-tuning
OptimalScale/gpt-neo2.7B-inst-tuning
```

Thanks you!

**Comment by shizhediao** [comment]
Closed. If you have any further questions, feel free to ask us~
Thank you!

**Comment by pckennethma** [comment]
Thanks for your prompt response! Probably you may also need to update the script in `output_models/download.sh`.
