### ISSUE TITLE
About finetuning details

### ISSUE THREAD

**Issue by xiaohangguo** [OptimalScale/LMFlow#541]
您好，很棒的工作，我看了您在Open MMlab 上的分享有两个问题想请教一下
1.第一个问题是微调思路的请教。我之前做过机器翻译的课程学习方法，这个在对于预训练模型在特殊domain数据（低资源）下是一种很好的训练方法。然后我看到习诗哲老师的分享指出fine tuning的范式是说第二部就是做这个领域数据的pre-training，想问一下这个特殊领域的语料我是不是应该抽离出来（现在我的数据集是一个包含了教材资料数据又包含了对话）。就是说分成多个json，一个json只包含这种无监督的领域的资料数据。另外的json包含这种有监督的对话的instruction tuning数据。这种方法是不是好一点？ 还是说我直接无脑塞，不用做数据的领域区分？
2.想问一下数据集的细节。看到您在文档里面写的数据格式是：
```
{
  "type": "text2text",
  "instances": [
    {
      "input": "Question: The Transformer architecture [START_REF]",
      "output": "N/A"
    },
    ...
  ]
}
```
但对于我的instruction数据是这样

```
{
        "instruction": "请尝试把这段文字写得更简单点，让大家都能明白。",
        "input": "令人欣喜的是，在知识经济大潮迅猛而来之际，一些发展中国家改变了过去“资源兴国”和“劳动力兴国”的发展战略，而走上科教兴国之路，并取得了可喜的成绩。",
        "output": "现在知识经济发展迅速，一些发展中国家过去选择“资源兴国”和“劳动力兴国”，现在转变为科教兴国，效果不错。"
    },
```
假设你们的这个格式`input`是` input1` 我下面的是`input2`
我需要对数据进行预处理的话，那么我需要做，`input1 = instruction + '\n'+'input2'`
这样处理然后整理好，再用lmflow来微调就可以了吧？

**Comment by xiaohangguo** [comment]
其实还有第三个问题，就是说问题里面，在这个`input1`成立的情况下，如果文本太长（一篇作文）的话会不会影响模型的能力，目前现有的研究是对于句子做语法句法的改错，但我们想做这种长文本的错误总结分析，您有什么建议吗

**Comment by shizhediao** [comment]
感谢关注！
1. 是的。最好是分离出来分成两个阶段进行训练： 无监督的continuous pretrain 和有监督的finetune
2. 是的。还有一种方式是：
```
{
  "type": "text2text",
  "instances": [
    {
      "input": "Instruction: 请尝试把这段文字写得更简单点，让大家都能明白。Input: 令人欣喜的是，在知识经济大潮迅猛xxxx",
      "output": "现在知识经济发展迅速，一些发展中国家过去选择“资源兴国”和“劳动力兴国xxxx"
    },
    ...
  ]
}
```

3. 长度在2048以内都没有问题

**Comment by xiaohangguo** [comment]
非常感谢，太棒了！另外还有一个请求，可以更新下文档里面的交流群（微信）交流群的二维码吗？我想加入进去，方便交流(#^.^#)

**Comment by shizhediao** [comment]
已更新，感谢提醒
<img width="512" alt="image" src="https://github.com/OptimalScale/LMFlow/assets/18120087/69d480bd-e55d-41b0-9758-e3b34b42e2b6">
