### ISSUE TITLE
Training details about Robin-v2

### ISSUE THREAD

**Issue by egrcc** [OptimalScale/LMFlow#558]
你好，看了robin v2相关模型的效果非常不错，但是似乎文章里并没有提及这个模型的训练细节。

1. 是用什么训练集训练的？
2. 有没有扩充中文词表更好支持中文生成？
3. 训练方式是什么，使用了lora吗？有没有rlhf？
4. 在 Hugging Face 上开源的模型也没有model card，希望能增加关于如何使用这个模型的说明。

不知道这些问题在哪里能找到答案呢？谢谢！

**Comment by shizhediao** [comment]
你好，感谢关注！
1. 训练数据集参考https://arxiv.org/pdf/2306.12420.pdf Section 4.2  训练数据已开源：http://lmflow.org:5000/lmflow_data.tar.gz
2. 目前的版本没有，未来会加上词表扩充
3. robin-v2是full training，没有rlhf
4. 感谢建议，后续会就爱上。
