### ISSUE TITLE
When it comes to verification,the model prdicted incomplete sentences

### ISSUE THREAD

**Issue by xiaohangguo** [OptimalScale/LMFlow#565]
batch_index157 rank0:
  ```
 question=['Input: Instruction: 请您将下面这篇文章中的语法错误修改为正确的形式，以提高其语法准确性。 Input: 我来中国以后已经过一年八个多月了。我一个人在异国他乡，时常给我打电话，时常寄给我包裹，包裹里面的东西都是我喜欢的。比如，药、日本特色的食品、日本的时装杂志等都在中国买不到的，我感到非常高兴。你们一直关怀我，我很感谢你们。我来中国以后，一次也没回国。爸爸、妈妈你们身体还好吗？我也很担心你们的身体情况。你们一定要保重。而且，现在我已经十分不熟悉日本的社会情况，所以现在我想日本。到暑假的时候，我打算回日本。我很想妈妈亲手做的菜。现在我非常盼暑假的到来。现在我在中国生活已经习惯了。我认识了很多同学。我每天去上课，学习情况也不错。我来中国之前，爸妈知道我下了去中国留学的决心，那时你们吃了一惊而对我表示强烈的反对。但是，最后，我到底来了中国。我现在没有后悔。因为我喜欢中国，我每天能学习汉语。老师教给我们讲话很仔细，我来中国以后得到了很多知识，我回日本以后要重新找工作。如果学会汉语的话，找工作一定有很大的帮助，我一定会对得起你们。那，到暑假时见面。有时我也给你们打电话。']
  prediction=[' 我来中国以后已经过了一年八个多月了。我一个人在异国他乡，时常给我打电话，时常寄给我包裹，包裹里面的东西都是我喜欢的。比如，药、日本特色的食品、日本的时装杂志等都在中国买不到的，我感到非常高兴。你们一直关怀我，我很感谢你们。我来中国以后，一次也没回国。爸爸、妈妈你们身体还好吗？我也很担心你们的身体情况。你们一定要保']

predicted answer: [' 我来中国以后已经过了一年八个多月了。我一个人在异国他乡，时常给我打电话，时常寄给我包裹，包裹里面的东西都是我喜欢的。比如，药、日本特色的食品、日本的时装杂志等都在中国买不到的，我感到非常高兴。你们一直关怀我，我很感谢你们。我来中国以后，一次也没回国。爸爸、妈妈你们身体还好吗？我也很担心你们的身体情况。你们一定要保'] 

groundtruth answer: ['我来中国以后已经一年八个多月了。我一个人在异国他乡，你们时常给我打电话，时常寄给我包裹，包裹里面的东西都是我喜欢的。比如，药、日本特色的食品、日本的时装杂志等在中国买不到的东西，我感到非常高兴。你们一直关怀我，我很感谢你们。我来中国以后，一次也没回国。爸爸、妈妈你们身体还好吗？我也很担心你们的身体情况。你们一定要保重。而且，现在我已经十分不熟悉日本的社会情况了，所以现在我想日本。到暑假的时候，我打算回日本。我很想妈妈亲手做的菜。现在我非常盼望暑假的到来。现在我在中国生活已经习惯了。我认识了很多同学。我每天去上课，学习情况也不错。我来中国之前，爸妈知道我下了去中国留学的决心，那时你们吃了一惊而对我表示强烈的反对。但是，最后，我到底来了中国。我现在没有后悔。因为我喜欢中国，我每天能学习汉语。老师教我们讲话很仔细，我来中国以后得到了很多知识，我回日本以后要重新找工作。如果学会汉语的话，对找工作一定有很大的帮助，我一定会对得起你们的。那，到暑假时见面。有时我也会给你们打电话的。'] 

```
这种情况是不是应该多训练几轮？这属于遗忘吧

**Comment by xiaohangguo** [comment]
> batch_index157 rank0:
> 
> ```
> question=['Input: Instruction: 请您将下面这篇文章中的语法错误修改为正确的形式，以提高其语法准确性。 Input: 我来中国以后已经过一年八个多月了。我一个人在异国他乡，时常给我打电话，时常寄给我包裹，包裹里面的东西都是我喜欢的。比如，药、日本特色的食品、日本的时装杂志等都在中国买不到的，我感到非常高兴。你们一直关怀我，我很感谢你们。我来中国以后，一次也没回国。爸爸、妈妈你们身体还好吗？我也很担心你们的身体情况。你们一定要保重。而且，现在我已经十分不熟悉日本的社会情况，所以现在我想日本。到暑假的时候，我打算回日本。我很想妈妈亲手做的菜。现在我非常盼暑假的到来。现在我在中国生活已经习惯了。我认识了很多同学。我每天去上课，学习情况也不错。我来中国之前，爸妈知道我下了去中国留学的决心，那时你们吃了一惊而对我表示强烈的反对。但是，最后，我到底来了中国。我现在没有后悔。因为我喜欢中国，我每天能学习汉语。老师教给我们讲话很仔细，我来中国以后得到了很多知识，我回日本以后要重新找工作。如果学会汉语的话，找工作一定有很大的帮助，我一定会对得起你们。那，到暑假时见面。有时我也给你们打电话。']
> prediction=[' 我来中国以后已经过了一年八个多月了。我一个人在异国他乡，时常给我打电话，时常寄给我包裹，包裹里面的东西都是我喜欢的。比如，药、日本特色的食品、日本的时装杂志等都在中国买不到的，我感到非常高兴。你们一直关怀我，我很感谢你们。我来中国以后，一次也没回国。爸爸、妈妈你们身体还好吗？我也很担心你们的身体情况。你们一定要保']
> 
> predicted answer: [' 我来中国以后已经过了一年八个多月了。我一个人在异国他乡，时常给我打电话，时常寄给我包裹，包裹里面的东西都是我喜欢的。比如，药、日本特色的食品、日本的时装杂志等都在中国买不到的，我感到非常高兴。你们一直关怀我，我很感谢你们。我来中国以后，一次也没回国。爸爸、妈妈你们身体还好吗？我也很担心你们的身体情况。你们一定要保'] 
> 
> groundtruth answer: ['我来中国以后已经一年八个多月了。我一个人在异国他乡，你们时常给我打电话，时常寄给我包裹，包裹里面的东西都是我喜欢的。比如，药、日本特色的食品、日本的时装杂志等在中国买不到的东西，我感到非常高兴。你们一直关怀我，我很感谢你们。我来中国以后，一次也没回国。爸爸、妈妈你们身体还好吗？我也很担心你们的身体情况。你们一定要保重。而且，现在我已经十分不熟悉日本的社会情况了，所以现在我想日本。到暑假的时候，我打算回日本。我很想妈妈亲手做的菜。现在我非常盼望暑假的到来。现在我在中国生活已经习惯了。我认识了很多同学。我每天去上课，学习情况也不错。我来中国之前，爸妈知道我下了去中国留学的决心，那时你们吃了一惊而对我表示强烈的反对。但是，最后，我到底来了中国。我现在没有后悔。因为我喜欢中国，我每天能学习汉语。老师教我们讲话很仔细，我来中国以后得到了很多知识，我回日本以后要重新找工作。如果学会汉语的话，对找工作一定有很大的帮助，我一定会对得起你们的。那，到暑假时见面。有时我也会给你们打电话的。'] 
> ```
> 
> 这种情况是不是应该多训练几轮？这属于遗忘吧
不知道是不是要训练奖励模型？不是很清楚，可以给我后面的训练做一些建议吗，上面是我只是LORA FINE TUNE跑了一个epoch

**Comment by shizhediao** [comment]
可以检查一下`max_new_tokens` 这个超参数，可能是生成长度不够，导致模型没有完成输出

**Comment by xiaohangguo** [comment]
> 可以检查一下`max_new_tokens` 这个超参数，可能是生成长度不够，导致模型没有完成输出
> 
> Can you please check the hyperparameter "max_new_tokens"? It might be the reason why the model did not complete the output due to insufficient generated length.

这是我的超参数配置，：
```
deepspeed ${deepspeed_args} \
  examples/finetune.py \
    --model_name_or_path output_models/baichuan_7b_1step_merged \
    --dataset_path ${dataset_path} \
    --output_dir ${output_dir} --overwrite_output_dir \
    --num_train_epochs 2 \
    --learning_rate 1e-4 \
    --block_size 512 \
    --per_device_train_batch_size 1 \
    --use_lora 1 \
    --lora_r 8 \
    --save_aggregated_lora 0\
    --deepspeed configs/ds_config_zero2.json \
    --bf16 \
    --run_name finetune_with_lora \
    --validation_split_percentage 0 \
    --logging_steps 20 \
    --do_train \
    --ddp_timeout 72000 \
    --save_steps 2000 \
    --dataloader_num_workers 1 \
    | tee ${log_dir}/train.log \
    2> ${log_dir}/train.err
```
`max_new_tokens`长度应该是默认参数

**Comment by xiaohangguo** [comment]
尝试添加以后好像提示没有这个参数，可能不是在这个脚本这里设置。如果不是可以告诉我在哪设置嘛？

`ValueError: Some specified arguments are not used by the HfArgumentParser: ['--max_new_tokens', '2000']`

```
(lmflow) hang@hang-System-Product-Name:~/桌面/LMFlow$ bash scripts/run_finetune_with_lora.sh 
[2023-07-25 17:50:29,648] [WARNING] [runner.py:186:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2023-07-25 17:50:29,657] [INFO] [runner.py:550:main] cmd = /home/hang/anaconda3/envs/lmflow/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=11000 --enable_each_rank_log=None examples/finetune.py --model_name_or_path output_models/baichuan_2b_1step_merged --dataset_path /home/hang/桌面/LMFlow/data/taoli_data_finetune/train --output_dir /home/hang/桌面/LMFlow/output_models/finetune_with_lora --overwrite_output_dir --num_train_epochs 2 --learning_rate 1e-4 --block_size 512 --per_device_train_batch_size 1 --use_lora 1 --lora_r 8 --save_aggregated_lora 0 --deepspeed configs/ds_config_zero3.json --bf16 --run_name finetune_with_lora --validation_split_percentage 0 --logging_steps 20 --do_train --ddp_timeout 72000 --max_new_tokens 2000 --save_steps 2000 --dataloader_num_workers 1
[2023-07-25 17:50:30,364] [INFO] [launch.py:142:main] WORLD INFO DICT: {'localhost': [0]}
[2023-07-25 17:50:30,364] [INFO] [launch.py:148:main] nnodes=1, num_local_procs=1, node_rank=0
[2023-07-25 17:50:30,364] [INFO] [launch.py:161:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
[2023-07-25 17:50:30,364] [INFO] [launch.py:162:main] dist_world_size=1
[2023-07-25 17:50:30,364] [INFO] [launch.py:164:main] Setting CUDA_VISIBLE_DEVICES=0

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/hang/anaconda3/envs/lmflow/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda116.so
/home/hang/anaconda3/envs/lmflow/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/home/hang/anaconda3/envs/lmflow/lib/libcudart.so'), PosixPath('/home/hang/anaconda3/envs/lmflow/lib/libcudart.so.11.0')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
CUDA SETUP: CUDA runtime path found: /home/hang/anaconda3/envs/lmflow/lib/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 116
CUDA SETUP: Loading binary /home/hang/anaconda3/envs/lmflow/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda116.so...
[2023-07-25 17:50:32,100] [INFO] [comm.py:652:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
Traceback (most recent call last):
  File "/home/hang/桌面/LMFlow/examples/finetune.py", line 61, in <module>
    main()
  File "/home/hang/桌面/LMFlow/examples/finetune.py", line 44, in main
    model_args, data_args, pipeline_args = parser.parse_args_into_dataclasses()
  File "/home/hang/anaconda3/envs/lmflow/lib/python3.9/site-packages/transformers/hf_argparser.py", line 341, in parse_args_into_dataclasses
    raise ValueError(f"Some specified arguments are not used by the HfArgumentParser: {remaining_args}")
ValueError: Some specified arguments are not used by the HfArgumentParser: ['--max_new_tokens', '2000']
[2023-07-25 17:50:33,371] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 7948
[2023-07-25 17:50:33,373] [ERROR] [launch.py:324:sigkill_handler] ['/home/hang/anaconda3/envs/lmflow/bin/python', '-u', 'examples/finetune.py', '--local_rank=0', '--model_name_or_path', 'output_models/baichuan_2b_1step_merged', '--dataset_path', '/home/hang/桌面/LMFlow/data/taoli_data_finetune/train', '--output_dir', '/home/hang/桌面/LMFlow/output_models/finetune_with_lora', '--overwrite_output_dir', '--num_train_epochs', '2', '--learning_rate', '1e-4', '--block_size', '512', '--per_device_train_batch_size', '1', '--use_lora', '1', '--lora_r', '8', '--save_aggregated_lora', '0', '--deepspeed', 'configs/ds_config_zero3.json', '--bf16', '--run_name', 'finetune_with_lora', '--validation_split_percentage', '0', '--logging_steps', '20', '--do_train', '--ddp_timeout', '72000', '--max_new_tokens', '2000', '-


```

**Comment by seanxuu** [comment]
> 尝试添加以后好像提示没有这个参数，可能不是在这个脚本这里设置。如果不是可以告诉我在哪设置嘛？
> 
> `ValueError: Some specified arguments are not used by the HfArgumentParser: ['--max_new_tokens', '2000']`
> 
> ```
> (lmflow) hang@hang-System-Product-Name:~/桌面/LMFlow$ bash scripts/run_finetune_with_lora.sh 
> [2023-07-25 17:50:29,648] [WARNING] [runner.py:186:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
> [2023-07-25 17:50:29,657] [INFO] [runner.py:550:main] cmd = /home/hang/anaconda3/envs/lmflow/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=11000 --enable_each_rank_log=None examples/finetune.py --model_name_or_path output_models/baichuan_2b_1step_merged --dataset_path /home/hang/桌面/LMFlow/data/taoli_data_finetune/train --output_dir /home/hang/桌面/LMFlow/output_models/finetune_with_lora --overwrite_output_dir --num_train_epochs 2 --learning_rate 1e-4 --block_size 512 --per_device_train_batch_size 1 --use_lora 1 --lora_r 8 --save_aggregated_lora 0 --deepspeed configs/ds_config_zero3.json --bf16 --run_name finetune_with_lora --validation_split_percentage 0 --logging_steps 20 --do_train --ddp_timeout 72000 --max_new_tokens 2000 --save_steps 2000 --dataloader_num_workers 1
> [2023-07-25 17:50:30,364] [INFO] [launch.py:142:main] WORLD INFO DICT: {'localhost': [0]}
> [2023-07-25 17:50:30,364] [INFO] [launch.py:148:main] nnodes=1, num_local_procs=1, node_rank=0
> [2023-07-25 17:50:30,364] [INFO] [launch.py:161:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
> [2023-07-25 17:50:30,364] [INFO] [launch.py:162:main] dist_world_size=1
> [2023-07-25 17:50:30,364] [INFO] [launch.py:164:main] Setting CUDA_VISIBLE_DEVICES=0
> 
> ===================================BUG REPORT===================================
> Welcome to bitsandbytes. For bug reports, please run
> 
> python -m bitsandbytes
> 
>  and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
> ================================================================================
> bin /home/hang/anaconda3/envs/lmflow/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda116.so
> /home/hang/anaconda3/envs/lmflow/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/home/hang/anaconda3/envs/lmflow/lib/libcudart.so'), PosixPath('/home/hang/anaconda3/envs/lmflow/lib/libcudart.so.11.0')}.. We'll flip a coin and try one of these, in order to fail forward.
> Either way, this might cause trouble in the future:
> If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
>   warn(msg)
> CUDA SETUP: CUDA runtime path found: /home/hang/anaconda3/envs/lmflow/lib/libcudart.so
> CUDA SETUP: Highest compute capability among GPUs detected: 8.6
> CUDA SETUP: Detected CUDA version 116
> CUDA SETUP: Loading binary /home/hang/anaconda3/envs/lmflow/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda116.so...
> [2023-07-25 17:50:32,100] [INFO] [comm.py:652:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
> Traceback (most recent call last):
>   File "/home/hang/桌面/LMFlow/examples/finetune.py", line 61, in <module>
>     main()
>   File "/home/hang/桌面/LMFlow/examples/finetune.py", line 44, in main
>     model_args, data_args, pipeline_args = parser.parse_args_into_dataclasses()
>   File "/home/hang/anaconda3/envs/lmflow/lib/python3.9/site-packages/transformers/hf_argparser.py", line 341, in parse_args_into_dataclasses
>     raise ValueError(f"Some specified arguments are not used by the HfArgumentParser: {remaining_args}")
> ValueError: Some specified arguments are not used by the HfArgumentParser: ['--max_new_tokens', '2000']
> [2023-07-25 17:50:33,371] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 7948
> [2023-07-25 17:50:33,373] [ERROR] [launch.py:324:sigkill_handler] ['/home/hang/anaconda3/envs/lmflow/bin/python', '-u', 'examples/finetune.py', '--local_rank=0', '--model_name_or_path', 'output_models/baichuan_2b_1step_merged', '--dataset_path', '/home/hang/桌面/LMFlow/data/taoli_data_finetune/train', '--output_dir', '/home/hang/桌面/LMFlow/output_models/finetune_with_lora', '--overwrite_output_dir', '--num_train_epochs', '2', '--learning_rate', '1e-4', '--block_size', '512', '--per_device_train_batch_size', '1', '--use_lora', '1', '--lora_r', '8', '--save_aggregated_lora', '0', '--deepspeed', 'configs/ds_config_zero3.json', '--bf16', '--run_name', 'finetune_with_lora', '--validation_split_percentage', '0', '--logging_steps', '20', '--do_train', '--ddp_timeout', '72000', '--max_new_tokens', '2000', '-
> ```
max_new_tokens is a parameter that used by inferencer. You can find the code below in args.py
```
max_new_tokens: int = field(
        default=100,
        metadata={"help": "Maximum length during inference."},
    )
```

**Comment by xiaohangguo** [comment]
如您所说默认的参数可以在args.py里面修改。我也查了官方的文档。有查到这个参数，并且是在inferencer，但您没告诉我之前我不知道是在args里面，
然后我应该在评价的脚本里面改参数，我之前是在训练里面改的，这个是一个错误。
现在成功了！在`run_evaluation_with_lora.sh`这个脚本里面也可以进行修改。
```
CUDA_VISIBLE_DEVICES=0 \
    deepspeed examples/evaluation.py \
    --answer_type text \
    --model_name_or_path fireballoon/baichuan-vicuna-chinese-7b \
    --lora_model_path output_models/finetune_with_lora/checkpoint-20986/adapter_model \
    --dataset_path data/taoli_data_finetune/test \
    --prompt_structure "Input: {input}" \
    --deepspeed examples/ds_config.json \
    --inference_batch_size_per_device 1 \
    --metric accuracy \
    --max_new_tokens 1024 
```

**Comment by xiaohangguo** [comment]
另外我想问一下funetune里面的脚本中的参数的一些含义，如果可以的话可以告诉我详细的文档介绍这种参数的位置吗
比如：`block_size`，
另外`max_train_samples`好像是我后续加的，不知道这个能不能限制或者扩大训练样本的长度呢？
```
deepspeed_args="--master_port=11000"      # Default argument
if [ $# -ge 1 ]; then
  deepspeed_args="$1"
fi

exp_id=finetune_with_lora
project_dir=$(cd "$(dirname $0)"/..; pwd)
output_dir=${project_dir}/output_models/${exp_id}
log_dir=${project_dir}/log/${exp_id}

dataset_path=${project_dir}/data/TED_data/step1

mkdir -p ${output_dir} ${log_dir}

deepspeed ${deepspeed_args} \
  examples/finetune.py \
    --model_name_or_path WizardLM/WizardLM-13B-V1.2 \
    --dataset_path ${dataset_path} \
    --output_dir ${output_dir} --overwrite_output_dir \
    --num_train_epochs 3.5 \
    --learning_rate 1e-4 \
    --block_size 512 \
    --per_device_train_batch_size 1 \
    --use_lora 1 \
    --lora_r 8 \
    --save_aggregated_lora 0\
    --deepspeed configs/ds_config_zero3.json \
    --bf16 \
    --run_name finetune_with_lora \
    --validation_split_percentage 0 \
    --logging_steps 20 \
    --do_train \
    --ddp_timeout 72000 \
    --max_train_samples 2048 \
    --save_steps 170 \
    --dataloader_num_workers 1 \
    | tee ${log_dir}/train.log \
    2> ${log_dir}/train.err
```

**Comment by seanxuu** [comment]
> 如您所说默认的参数可以在args.py里面修改。我也查了官方的文档。有查到这个参数，并且是在inferencer，但您没告诉我之前我不知道是在args里面， 然后我应该在评价的脚本里面改参数，我之前是在训练里面改的，这个是一个错误。 现在成功了！在`run_evaluation_with_lora.sh`这个脚本里面也可以进行修改。
> 
> ```
> CUDA_VISIBLE_DEVICES=0 \
>     deepspeed examples/evaluation.py \
>     --answer_type text \
>     --model_name_or_path fireballoon/baichuan-vicuna-chinese-7b \
>     --lora_model_path output_models/finetune_with_lora/checkpoint-20986/adapter_model \
>     --dataset_path data/taoli_data_finetune/test \
>     --prompt_structure "Input: {input}" \
>     --deepspeed examples/ds_config.json \
>     --inference_batch_size_per_device 1 \
>     --metric accuracy \
>     --max_new_tokens 1024 
> ```

Yes, we use` parser = HfArgumentParser((ModelArguments, DatasetArguments, PipelineArguments))` to catch all related args from command-line interface, so you definitely can add these args in the shell script you run.

**Comment by xiaohangguo** [comment]
> > 如您所说默认的参数可以在args.py里面修改。我也查了官方的文档。有查到这个参数，并且是在inferencer，但您没告诉我之前我不知道是在args里面， 然后我应该在评价的脚本里面改参数，我之前是在训练里面改的，这个是一个错误。 现在成功了！在`run_evaluation_with_lora.sh`这个脚本里面也可以进行修改。
> > ```
> > CUDA_VISIBLE_DEVICES=0 \
> >     deepspeed examples/evaluation.py \
> >     --answer_type text \
> >     --model_name_or_path fireballoon/baichuan-vicuna-chinese-7b \
> >     --lora_model_path output_models/finetune_with_lora/checkpoint-20986/adapter_model \
> >     --dataset_path data/taoli_data_finetune/test \
> >     --prompt_structure "Input: {input}" \
> >     --deepspeed examples/ds_config.json \
> >     --inference_batch_size_per_device 1 \
> >     --metric accuracy \
> >     --max_new_tokens 1024 
> > ```
> 
> Yes, we use` parser = HfArgumentParser((ModelArguments, DatasetArguments, PipelineArguments))` to catch all related args from command-line interface, so you definitely can add these args in the shell script you run.

Thanks a lot.I see that in the terminal logs.It is true.

**Comment by seanxuu** [comment]
> 另外我想问一下funetune里面的脚本中的参数的一些含义，如果可以的话可以告诉我详细的文档介绍这种参数的位置吗 比如：`block_size`， 另外`max_train_samples`好像是我后续加的，不知道这个能不能限制或者扩大训练样本的长度呢？
> 
> ```
> deepspeed_args="--master_port=11000"      # Default argument
> if [ $# -ge 1 ]; then
>   deepspeed_args="$1"
> fi
> 
> exp_id=finetune_with_lora
> project_dir=$(cd "$(dirname $0)"/..; pwd)
> output_dir=${project_dir}/output_models/${exp_id}
> log_dir=${project_dir}/log/${exp_id}
> 
> dataset_path=${project_dir}/data/TED_data/step1
> 
> mkdir -p ${output_dir} ${log_dir}
> 
> deepspeed ${deepspeed_args} \
>   examples/finetune.py \
>     --model_name_or_path WizardLM/WizardLM-13B-V1.2 \
>     --dataset_path ${dataset_path} \
>     --output_dir ${output_dir} --overwrite_output_dir \
>     --num_train_epochs 3.5 \
>     --learning_rate 1e-4 \
>     --block_size 512 \
>     --per_device_train_batch_size 1 \
>     --use_lora 1 \
>     --lora_r 8 \
>     --save_aggregated_lora 0\
>     --deepspeed configs/ds_config_zero3.json \
>     --bf16 \
>     --run_name finetune_with_lora \
>     --validation_split_percentage 0 \
>     --logging_steps 20 \
>     --do_train \
>     --ddp_timeout 72000 \
>     --max_train_samples 2048 \
>     --save_steps 170 \
>     --dataloader_num_workers 1 \
>     | tee ${log_dir}/train.log \
>     2> ${log_dir}/train.err
> ```

Please refer to the comments in [args.py](https://github.com/OptimalScale/LMFlow/blob/main/src/lmflow/args.py)

**Comment by xiaohangguo** [comment]
> > 另外我想问一下funetune里面的脚本中的参数的一些含义，如果可以的话可以告诉我详细的文档介绍这种参数的位置吗 比如：`block_size`， 另外`max_train_samples`好像是我后续加的，不知道这个能不能限制或者扩大训练样本的长度呢？
> > ```
> > deepspeed_args="--master_port=11000"      # Default argument
> > if [ $# -ge 1 ]; then
> >   deepspeed_args="$1"
> > fi
> > 
> > exp_id=finetune_with_lora
> > project_dir=$(cd "$(dirname $0)"/..; pwd)
> > output_dir=${project_dir}/output_models/${exp_id}
> > log_dir=${project_dir}/log/${exp_id}
> > 
> > dataset_path=${project_dir}/data/TED_data/step1
> > 
> > mkdir -p ${output_dir} ${log_dir}
> > 
> > deepspeed ${deepspeed_args} \
> >   examples/finetune.py \
> >     --model_name_or_path WizardLM/WizardLM-13B-V1.2 \
> >     --dataset_path ${dataset_path} \
> >     --output_dir ${output_dir} --overwrite_output_dir \
> >     --num_train_epochs 3.5 \
> >     --learning_rate 1e-4 \
> >     --block_size 512 \
> >     --per_device_train_batch_size 1 \
> >     --use_lora 1 \
> >     --lora_r 8 \
> >     --save_aggregated_lora 0\
> >     --deepspeed configs/ds_config_zero3.json \
> >     --bf16 \
> >     --run_name finetune_with_lora \
> >     --validation_split_percentage 0 \
> >     --logging_steps 20 \
> >     --do_train \
> >     --ddp_timeout 72000 \
> >     --max_train_samples 2048 \
> >     --save_steps 170 \
> >     --dataloader_num_workers 1 \
> >     | tee ${log_dir}/train.log \
> >     2> ${log_dir}/train.err
> > ```
> 
> Please refer to the comments in [args.py](https://github.com/OptimalScale/LMFlow/blob/main/src/lmflow/args.py)

非常感谢！请你原谅我有这么多问题，我还有最后一个问题，请问可以给我推荐一些代码生成的模型吗？代码能力较强的那种

**Comment by shizhediao** [comment]
You might want to refer to StarCoder: https://arxiv.org/abs/2305.06161

**Comment by xiaohangguo** [comment]
> You might want to refer to StarCoder: https://arxiv.org/abs/2305.06161

thanks，i paying attention to StarCoder、wizard、pangu-coder2.
