### ISSUE TITLE
How to use position interpolation

### ISSUE THREAD

**Issue by pangwenfeng** [OptimalScale/LMFlow#586]
Thank you for your work. I noticed that you have added support for positional interpolation! Could you provide a specific example or instructions such as the example of config file on how to use this feature? Additionally, while reading the code, I found that your implementation differs from LongChat, especially in using two parameters. Could you please explain in detail the purpose and design approach of these parameters? Thank you very much.

**Comment by pangwenfeng** [comment]
I was wondering if anyone could assist me？

**Comment by research4pan** [comment]
@yaoguany Could you please look into this problem?

**Comment by yaoguany** [comment]
# How to use this feature:
You can check out this link to see how to use this feature:
[Position_Interpolation](https://github.com/OptimalScale/LMFlow/blob/main/readme/Position_Interpolation.md)

# Two parameters
We support both linear and NTK interpolation so there will be two parameters. More advanced than the official library, our codes allows you to simultaneously use both linear and NTK interpolation. Just set the ratio as:
```
--rope_pi_ratio 2 \
--rope_ntk_ratio 4 \
```

**Comment by pangwenfeng** [comment]
Thanks for your reply! I want to confirm two thing

1. If the original input length is 1024 and I want to extend it to 4096 during the training stage, is the configuration below correct?
`
--truncate_to_model_max_length False
--do_rope_scaling True
--rope_pi_ratio 2 \
--rope_ntk_ratio 4 \
--block_size 4096
`

2. Is the example you provided below for extending the input length from 512 to 4098 during the inference stage?
'
CUDA_VISIBLE_DEVICES=0 \
    deepspeed examples/evaluation.py \
    --answer_type text \
    --model_name_or_path pinkmanlove/llama-7b-hf \
    --dataset_path data/wiki_en_eval \
    --deepspeed examples/ds_config.json \
    --inference_batch_size_per_device 1 \
    --truncate_to_model_max_length False \
    --block_size 4096 \
    --use_flash_attention True \
    --do_rope_scaling True \
    --rope_pi_ratio 2 \
    --rope_ntk_ratio 4 \
    --metric ppl
‘

**Comment by yaoguany** [comment]
1.No,the scaling ratio is pi_ratio*ntk_ratio. So in this case you are scaling to 8192
2.Same as 1, you can set either pi_ratio or ntk_ratio to 4, or set both pi_ratio and ntk_ratio to2

**Comment by pangwenfeng** [comment]
1. so in the question 1 should I set block_size as 8192 if the target input length is 8192?
2.  does it mean that because the scaling ratio is 8, the model now supports the max length is 2048*8 and the largest number of block_size I can set is 2048*8?

**Comment by yaoguany** [comment]
1. No,you can still set the block size to 4096 even if scaling length is 8192
2. The model supports max length is 16384 for that case ,but if you set the block size to 16384, there may be some drops on the performance because the length is much longer than the original one. \
In our test, the model still works well on 7000 block size under this scaling ratio set,

**Comment by pangwenfeng** [comment]
Thank for your patient reply! I still have a little confusion that why I can set the block_size to 4096 even if the target length is 8192. Does it mean that if my target length is 8192, the model can work even the block_size is 4096, but I can get better performance if I set it to 8192? Thanks again!

**Comment by yaoguany** [comment]
Yse,you can check this [link](https://www.reddit.com/r/LocalLLaMA/comments/14lz7j5/ntkaware_scaled_rope_allows_llama_models_to_have/)

**Comment by pangwenfeng** [comment]
Thank you very much! I will check it~
