### ISSUE TITLE
dataset hh_rlhf.tar.gz file might be broken

### ISSUE THREAD

**Issue by sugarfreeLiuYuXuan** [OptimalScale/LMFlow#587]
http://lmflow.org:5000/hh_rlhf.tar.gz might be broken, I download from this and can't get this file "hh_rlhf_rm_training.json"

**Comment by sugarfreeLiuYuXuan** [comment]
when tar -zxvf I got：
._hh_rlhf
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.macl'
hh_rlhf/
hh_rlhf/._rlhf
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
hh_rlhf/rlhf/
hh_rlhf/._sft
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
hh_rlhf/sft/
hh_rlhf/._rm
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
hh_rlhf/rm/
hh_rlhf/rm/._hh_rlhf_rm_data.json
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
hh_rlhf/rm/hh_rlhf_rm_data.json

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

**Comment by sugarfreeLiuYuXuan** [comment]
Please ensure that there is no problem with the hh_rlhf.tar.gz file you placed on the http://lmflow.org:5000/hh_rlhf.tar.gz website, as I have downloaded it three times repeatedly.

**Comment by shizhediao** [comment]
Could you try `wget http://lmflow.org:5000/hh_rlhf.tar.gz`?
It works well in my setting.

**Comment by sugarfreeLiuYuXuan** [comment]
I downloaded the file at the address you mentioned, next I ran tar -zxvf normally then my directory is shown below：
├── hh_rlhf
│   ├── rlhf
│   ├── rm
│   │   └── hh_rlhf_rm_data.json
│   └── sft
├── hh_rlhf.tar.gz
 I'm confused why there is only the file hh_rlhf_rm_data.json, there are no files in the rlhf and sft directories, and at the same time, there is an error when unzipping it：._hh_rlhf
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.macl'
hh_rlhf/
hh_rlhf/._rlhf
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
hh_rlhf/rlhf/
hh_rlhf/._sft
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
hh_rlhf/sft/
hh_rlhf/._rm
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
hh_rlhf/rm/
hh_rlhf/rm/._hh_rlhf_rm_data.json
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
hh_rlhf/rm/hh_rlhf_rm_data.json

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
can you helpl me， thx~

**Comment by sugarfreeLiuYuXuan** [comment]
> Could you try `wget http://lmflow.org:5000/hh_rlhf.tar.gz`? It works well in my setting.

I downloaded the file at the address you mentioned, next I ran tar -zxvf normally then my directory is shown below：
├── hh_rlhf
│ ├── rlhf
│ ├── rm
│ │ └── hh_rlhf_rm_data.json
│ └── sft
├── hh_rlhf.tar.gz
I'm confused why there is only the file hh_rlhf_rm_data.json, there are no files in the rlhf and sft directories, and at the same time, there is an error when unzipping it：._hh_rlhf
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.macl'
hh_rlhf/
hh_rlhf/._rlhf
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
hh_rlhf/rlhf/
hh_rlhf/._sft
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
hh_rlhf/sft/
hh_rlhf/._rm
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
hh_rlhf/rm/
hh_rlhf/rm/._hh_rlhf_rm_data.json
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'
hh_rlhf/rm/hh_rlhf_rm_data.json

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
can you helpl me， thx~

**Comment by shizhediao** [comment]
There might be errors during your download. Could you please check the process and logs during downloading?
Thanks!

**Comment by sugarfreeLiuYuXuan** [comment]
> There might be errors during your download. Could you please check the process and logs during downloading? Thanks!

您好😂，我确实网络没问题，当我运行cd data && ./download.sh hh_rlhf && cd - 时，这是我的输出结果：
downloading hh_rlhf dataset
--2023-08-07 00:37:11--  http://lmflow.org:5000/hh_rlhf.tar.gz
正在解析主机 lmflow.org (lmflow.org)... 3.84.211.127
正在连接 lmflow.org (lmflow.org)|3.84.211.127|:5000... 已连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度：64819200 (62M) [application/gzip]
正在保存至: “hh_rlhf.tar.gz”

hh_rlhf.tar.gz       100%[=====================>]  61.82M  10.1MB/s  用时 7.5s    

2023-08-07 00:37:19 (8.20 MB/s) - 已保存 “hh_rlhf.tar.gz” [64819200/64819200])

x hh_rlhf/
x hh_rlhf/rlhf/
x hh_rlhf/sft/
x hh_rlhf/rm/
x hh_rlhf/rm/hh_rlhf_rm_data.json: truncated gzip input
tar: Error exit delayed from previous errors.
~/myCode/LMFlow-main
确实看下载的时候是没有问题的😂，在解压的时候，就出现这个错误x hh_rlhf/
x hh_rlhf/rlhf/
x hh_rlhf/sft/
x hh_rlhf/rm/
x hh_rlhf/rm/hh_rlhf_rm_data.json: truncated gzip input
tar: Error exit delayed from previous errors.
我发现子目录下就rm只有hh_rlhf_rm_data.json文件，其他的子目录下rlhf、sft都是空的文件，您可以给我一个其他的方法下载这个数据集吗？我想浮现你们杰出的工作，谢谢啦

**Comment by shizhediao** [comment]
你好，经过检查，确实是我们最近上传的文件出了问题，目前已修复，多谢反馈和您的耐心等待，谢谢！

------

Indeed there was a problem with the file we recently uploaded. It has now been fixed. Thank you for your feedback and your patient waiting. Thanks
