### ISSUE TITLE
About Finetune datasets

### ISSUE THREAD

**Issue by xiaohangguo** [OptimalScale/LMFlow#608]
微调SFT中，发现真正finetune的数据好像应该是text_only类型的，并且好像这种格式要好一点，总之就是吧上下文应该是全放在一条数据里面
```
{
  "type": "text_only",
  "instances": [
    {
      "text": "### Instruction: TED中有哪些内置的逻辑门函数？ \n ### Response: TED中提供了一些内置的逻辑门函数，用于方便地构建逻辑电路。一些常见的内置逻辑门函数包括：……   \n\n"
    },
    ……
    {
```
或者
```
{
  "type": "text_only",
  "instances": [
    {
      "text": "### Instruction: TED中有哪些内置的逻辑门函数？### Input: <additional context> \n ### Response: TED中提供了一些内置的逻辑门函数，用于方便地构建逻辑电路。一些常见的内置逻辑门函数包括：……   \n\n"
    },

```
我试着用QA对的type为text2text的数据进行SFT，好像会导致模型直接乱输出。
`text2text`类型数据是为了benchmarak以及便于推理吧？而并非训练？
另外：
我想问一下是直接在instruction后面加上上下文内容，比如一个函数，或者其他限定知识。这种方式好呢？还是
`### Instruction: TED中有哪些内置的逻辑门函数？+<additional context>  \n `
还是说这样好一点？
`### Instruction: TED中有哪些内置的逻辑门函数？\n ### Input: <additional context> \n ### Response: TED中提供了一些内置的逻辑门函数，用于方便地构建逻辑电路。一些常见的内置逻辑门函数包括：……   \n\n`

**Comment by shizhediao** [comment]
`text2text` 也是适合训练的，我们使用这种格式也可以训练出好的模型。理论上这种方式减少了对input的loss计算，会更加高效一些。

**Comment by xiaohangguo** [comment]
> `text2text` 也是适合训练的，我们使用这种格式也可以训练出好的模型。理论上这种方式减少了对input的loss计算，会更加高效一些。
> 
> 看起来第二种好一些，不过注意第二种里面用了###来分割，最好是将终止符提前定义清晰。一般来说常见的终止符有### 或者\n 二者选一个。

1.谢谢，那可能是我选的底座模型是不对的（wizard-7b），利用这种text2text数据集来训练的时候loss完全不降，我调用未经训练的模型，输出也是乱码，很怪。但我用text_only的数据微调Chinese-llama2-7b的时候是有效果的，两个数据集除了type不同，实际内容都是一样的。如果按照你所说的，都能成功，那肯定是基座模型的问题。

2.提前定义清楚的意思是说，我的数据集里面都采用这二选一的其中一个吧？我把两种方式按照我的理解都写一遍，你看对不对。
（1）\n终止符
`Instruction: TED中有哪些内置的逻辑门函数？\n  Input: <additional context> \n Response: TED中提供了一些内置的逻辑门函数，用于方便地构建逻辑电路。一些常见的内置逻辑门函数包括：……   \n`
（2）###终止符
`###Instruction: TED中有哪些内置的逻辑门函数？ ###Input: <additional context> ### Response: TED中提供了一些内置的逻辑门函数，用于方便地构建逻辑电路。一些常见的内置逻辑门函数包括：……   ###`

总感觉\n换行符来当做终止符的时候有点怪，因为有时候我们是为了换行嘛，所以一般\n成对出现的时候才代表终止，是这样理解吗？

**Comment by shizhediao** [comment]
二选一就好。\n是传统用法，可能看成换行就是句子终止。当然可以用###

**Comment by xiaohangguo** [comment]
我感觉\n 在input里面是代码块的话，很容易出问题，这个观点你认可吗？

**Comment by shizhediao** [comment]
两者都可以，只要finetune和inference保持一致就好

**Comment by xiaohangguo** [comment]
无敌，了解。过了好久了，之前get到了
