### ISSUE TITLE
ERROR: No matching distribution found for lmflow.datasets when running [python app.py]

### ISSUE THREAD

**Issue by alexhmyang** [OptimalScale/LMFlow#61]
(base) u20@u20:~/LMFlow/service$ python app.py
Traceback (most recent call last):
  File "app.py", line 4, in <module>
    from lmflow.datasets.dataset import Dataset
ModuleNotFoundError: No module named 'lmflow.datasets'

(base) u20@u20:~/LMFlow/service$ pip install lmflow.datasets
ERROR: Could not find a version that satisfies the requirement lmflow.datasets (from versions: none)
ERROR: No matching distribution found for lmflow.datasets

**Comment by yslz** [comment]
I met this error too...how to fix?

**Comment by alexhmyang** [comment]
> I met this error too...how to fix?

conda activate lmflow
and use  lmflow env to run python (you may run python outside  lmflow env )

**Comment by Matrixsun** [comment]
first, you should  install lmflow  by `pip install -e .` in `./LMFlow`. Then  it is ok
