### ISSUE TITLE
Hope to get in touch

### ISSUE THREAD

**Issue by JimmyMa99** [OptimalScale/LMFlow#610]
Dear [LMFlow](https://github.com/OptimalScale/LMFlow),
Greetings! I am Jimmy, a community developer and volunteer at InternLM. Your work has been immensely beneficial to me, and I believe it can be effectively utilized in InternLM as well. Welcome to add Discord https://discord.gg/gF9ezcmtM3 . I hope to get in touch with you.

Best regards,
Jimmy

**Comment by shizhediao** [comment]
Hi,
Thanks for reaching out.
Welcome to join our community https://discord.gg/u9VJNpzhvA
