### ISSUE TITLE
why do I repeating ouput?

### ISSUE THREAD

**Issue by xiaohangguo** [OptimalScale/LMFlow#617]
不好意思，我是小白，帮我看看吧TnT,不知道是不是和基底模型的prompt格式不对？
1.
![image](https://github.com/OptimalScale/LMFlow/assets/72799392/2992884a-eb5f-4357-9045-bcb829d48265)
2.
![image](https://github.com/OptimalScale/LMFlow/assets/72799392/4998678a-da9c-438d-aff7-8d13627f98e9)
3.
![image](https://github.com/OptimalScale/LMFlow/assets/72799392/8814ae64-bd37-4e75-98ca-9bc240d447a7)

**Comment by shizhediao** [comment]
请问使用的是什么基座模型？

**Comment by xiaohangguo** [comment]
`https://huggingface.co/LinkSoul/Chinese-Llama-2-7b`
我改成###Human ###Assistant以后 得到了改善，不过我又发现了又新的问题
###instruction ###input ###ouput 也可以，但模型输出会有很多\n 
比如：
###instruction: 请问TED指什么？ ###input: N/A ###output:
TED是xxxxx \n \n \n \n \n Markdown的形式，就猛回车了

**Comment by shizhediao** [comment]
检查一下训练集，我们没有用过这个基座模型，需要检查一下原模型的训练过程

**Comment by xiaohangguo** [comment]
> 检查一下训练集，我们没有用过这个基座模型，需要检查一下原模型的训练过程

ok，明白了
