### ISSUE TITLE
About the eos token

### ISSUE THREAD

**Issue by nicosouth** [OptimalScale/LMFlow#626]
hi, i have a question about eos token.

In the file(hf_decoder_model.py), i find that you use the class of AutoTokenizer. i want to know if it will add the eos token automatically.

**Comment by shizhediao** [comment]
Different models have different behaviors on the eos token. If there is a specification of eos token in the model config, then it will add the eos token. Otherwise, the eos token will be None. Thanks!

**Comment by nicosouth** [comment]
do you mean it will be defined in the tokenizer_config.json?
I did find that there is a parameter "add_eos_token" in this file.

thank you!

**Comment by shizhediao** [comment]
yes you can modify it according to your setting.

**Comment by nicosouth** [comment]
thank you!
