### ISSUE TITLE
module named 'lmflow.args'

### ISSUE THREAD

**Issue by JenniePing** [OptimalScale/LMFlow#637]
**Describe the bug**
./scripts/finetune.sh ERROR: module named 'lmflow.args'

I've already installed lmflow, what's going on here, please? Maybe coz I cannot run bash ./install.sh well, which got ERROR: Could not build wheels for flash-attn, which is required to install pyproject.toml-based projects. How can I fix it up, please?

**Comment by Aiden0526** [comment]
You need to do

**Comment by JenniePing** [comment]
> You need to do python setup.py install

Thank you for your replay! But I keep having Errors when install, seems like there are a lot of environment problems. Did anyone else deploy this well? Could you please tell us your WeChat group, please? The contact you put on your web has already been out of date.

**Comment by shizhediao** [comment]
Hi the qrcode has been updated.
Thanks!

**Comment by JenniePing** [comment]
> Hi the qrcode has been updated.
> Thanks!

Thank you very much for your reply!! But it stills says the QRcode was expired on August 23rd :(

**Comment by shizhediao** [comment]
oh will update it. 
Please look at this one for now: https://i.ibb.co/kKvGhPr/Wechat-IMG1129.jpg

**Comment by cauwulixuan** [comment]
> oh will update it. Please look at this one for now: https://i.ibb.co/kKvGhPr/Wechat-IMG1129.jpg

could you update the wechat group qrcode again? this one has been expired too. Thanks...

**Comment by shizhediao** [comment]
Hi,
Please use this updated one. Thanks
![11381696099544_ pic](https://github.com/OptimalScale/LMFlow/assets/18120087/0497e2a1-e5e6-49c4-87dd-e8044b040350)
