### ISSUE TITLE
wandb: ERROR api_key not configured (no-tty) ...

### ISSUE THREAD

**Issue by wangyan-hlab** [OptimalScale/LMFlow#65]
Hi,

When I run the fine-tuning script
`./scripts/run_finetune.sh`

Some errors occur:
> ```
> wandb: ERROR api_key not configured (no-tty). call wandb.login(key=[your_api_key])
> Traceback (most recent call last):
>   File "/home/yan/Documents/LMFlow/examples/finetune.py", line 70, in <module>
>     main()
>   File "/home/yan/Documents/LMFlow/examples/finetune.py", line 66, in main
>     tuned_model = finetuner.tune(model=model, lm_dataset=lm_dataset)
>   File "/home/yan/Documents/LMFlow/src/lmflow/pipeline/finetuner.py", line 232, in tune
>     train_result = trainer.train(resume_from_checkpoint=checkpoint)
>   File "/home/yan/anaconda3/envs/lmflow/lib/python3.9/site-packages/transformers/trainer.py", line 1639, in train
>     return inner_training_loop(
>   File "/home/yan/anaconda3/envs/lmflow/lib/python3.9/site-packages/transformers/trainer.py", line 1822, in _inner_training_loop
>     self.control = self.callback_handler.on_train_begin(args, self.state, self.control)
>   File "/home/yan/anaconda3/envs/lmflow/lib/python3.9/site-packages/transformers/trainer_callback.py", line 353, in on_train_begin
>     return self.call_event("on_train_begin", args, state, control)
>   File "/home/yan/anaconda3/envs/lmflow/lib/python3.9/site-packages/transformers/trainer_callback.py", line 397, in call_event
>     result = getattr(callback, event)(
>   File "/home/yan/anaconda3/envs/lmflow/lib/python3.9/site-packages/transformers/integrations.py", line 764, in on_train_begin
>     self.setup(args, state, model, **kwargs)
>   File "/home/yan/anaconda3/envs/lmflow/lib/python3.9/site-packages/transformers/integrations.py", line 738, in setup
>     self._wandb.init(
>   File "/home/yan/anaconda3/envs/lmflow/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1140, in init
>     wi.setup(kwargs)
>   File "/home/yan/anaconda3/envs/lmflow/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 288, in setup
>     wandb_login._login(
>   File "/home/yan/anaconda3/envs/lmflow/lib/python3.9/site-packages/wandb/sdk/wandb_login.py", line 298, in _login
>     wlogin.prompt_api_key()
>   File "/home/yan/anaconda3/envs/lmflow/lib/python3.9/site-packages/wandb/sdk/wandb_login.py", line 228, in prompt_api_key
>     raise UsageError("api_key not configured (no-tty). call " + directive)
> wandb.errors.UsageError: api_key not configured (no-tty). call wandb.login(key=[your_api_key])
> [2023-04-03 10:07:42,282] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 16203
> [2023-04-03 10:07:42,283] [ERROR] [launch.py:324:sigkill_handler] ['/home/yan/anaconda3/envs/lmflow/bin/python', '-u', 'examples/finetune.py', '--local_rank=0', '--model_name_or_path', 'gpt2', '--dataset_path', '/home/yan/Documents/LMFlow/data/alpaca/train', '--output_dir', '/home/yan/Documents/LMFlow/output_models/finetune', '--overwrite_output_dir', '--num_train_epochs', '0.01', '--learning_rate', '2e-5', '--block_size', '512', '--per_device_train_batch_size', '1', '--deepspeed', 'configs/ds_config_zero3.json', '--bf16', '--run_name', 'finetune', '--validation_split_percentage', '0', '--logging_steps', '20', '--do_train', '--ddp_timeout', '72000', '--save_steps', '5000', '--dataloader_num_workers', '1'] exits with return code = 1
> ```

Would you please provide some advice?

**Comment by shizhediao** [comment]
Hi,
It could be solved by typing `wandb init` in the command line. Then you could authorize your account by clicking on the prompted link. If you still encounter some issues, feel free to ask us.

Thanks!

**Comment by ashokchhetri7** [comment]
Hey,

In Jupyter notebook sometimes this works:

use:

`!wandb login`


And paste the API key at the end of the below shown line;

Paste an API key from your profile and hit enter, or press ctrl+c to quit: [_**Paste it here, This will be not visible**_]

**Comment by mervess** [comment]
In case anyone else facing that issue on a cluster based system solely relying on terminal like I did:

What worked for me was, not running the commands on terminal, but running a small python script having `wandb init` inside, so that I was finally able to enter my API key.
