### ISSUE TITLE
A6000 support for FlashAttentionV2

### ISSUE THREAD

**Issue by zhangliang-04** [OptimalScale/LMFlow#665]
**Is your feature request related to a problem? Please describe.**
It seems that this codebase only supports the use of FlashAttentionV2 on A100 or A40. However,  in theory all Turing or Ampere GPUs should work with it. Is there any plan for supporting A6000?

**Describe the solution you'd like**
Add FlashAttention support for A6000 gpu.

**Comment by research4pan** [comment]
Thanks for pointing that out! Yeah I think it is totally possible, and all the required change is this line in `install.sh` (https://github.com/OptimalScale/LMFlow/blob/main/install.sh#L6). I will modify it soon when I have some time. Also, if you are interested in contributing, we welcome all kinds of contributions via PR. Thanks 😄

**Comment by research4pan** [comment]
We have updated `install.sh` accordingly (https://github.com/OptimalScale/LMFlow/pull/669). Could you please let us know if the problem is solved? Thanks 😄

**Comment by zhangliang-04** [comment]
Yes, it works! Thanks for your contribution😄
