### ISSUE TITLE
[BUG]./scripts/run_finetune_with_lora_save_aggregated_weights.sh

### ISSUE THREAD

**Issue by shuishui616** [OptimalScale/LMFlow#672]
When I run ./scripts/run_finetune_with_lora_save_aggregated_weights.sh
ValueError: Empty 'data_files': '[]'. It should be either non-empty or None (default).

**Comment by Dada-Cloudzxy** [comment]
Hello! I have also encountered this problem, how can I solve it?

**Comment by Dada-Cloudzxy** [comment]
@shuishui616

**Comment by research4pan** [comment]
Thanks for your interest in LMFlow! You may check the data format and test it with SFT first. Also, it would be nice if you could provide a screenshot about the error so we could examine that for you. Thanks very much 😄

**Comment by sararous** [comment]
您好，请问这个问题解决了吗？我也遇到了这个问题
