### ISSUE TITLE
[BUG] Conflict dependencies of package versions

### ISSUE THREAD

**Issue by YourSaDady** [OptimalScale/LMFlow#695]
**Describe the bug**
I tried to set up the LMFlow environments following the README.md instructions. After I run the line `bash install.sh`, I encountered a conflict dependencies error described in the screenshot.

**To Reproduce**
1. `git clone -b v0.0.5 https://github.com/OptimalScale/LMFlow.git`
2. `cd LMFlow`
3. `conda create -n lmflow python=3.9 -y`
4. `conda activate lmflow`
5. `conda install mpi4py`
6. `bash install.sh`
7. See error

**Expected behavior**
no error should appear after this line

**Screenshots**
<img width="852" alt="error" src="https://github.com/OptimalScale/LMFlow/assets/99607923/22278d6e-e39b-40df-8d77-1bb7e05389ea">

**Desktop (please complete the following information):**
 - OS: Win11 (WSL)
 - Browser chrome

**Additional context**
Please tell me how to reslove this, thanks!

**Comment by research4pan** [comment]
Thanks for your interest in LMFlow! In that case, you may use the main branch via `git clone https://github.com/OptimalScale/LMFlow.git`. We will mark current branch as `v0.0.6` and update `README.md` soon. Thanks 😄
