### ISSUE TITLE
Multiple rounds of training

### ISSUE THREAD

**Issue by Yummy416** [OptimalScale/LMFlow#731]
Hello, if I want to train vicuna for multiple rounds of dialogue, how should I format the data set? Can you give me an example? Thanks

**Comment by research4pan** [comment]
Thanks for your interest in LMFlow! You may utilize our recently integrated "ShareGPT" format, whose `*.json` file has a format as follows,

### Conversation

>  **Work in Progess:** We are rapidly working on this data format.

Conversational data are commonly used in sft process. We currently support conversational data in ShareGPT format:
```json
{
  "type": "conversation",
  "instances": [
    {
      "conversation_id": "CONVERSATION_ID",
      "system": "SYSTEM_PROPMT",
      "tools": ["TOOL_DESCRIPTION_1","TOOL_DESCRIPTION_2","TOOL_DESCRIPTION_X"],
      "messages": [
        {
            "role": "user",
            "content": "USER_INPUT_1"
        },
        {
            "role": "assistant",
            "content": "ASSISTANT_RESPONSE_1"
        },
        {
            "role": "user",
            "content": "USER_INPUT_2"
        },
        {
            "role": "assistant",
            "content": "ASSISTANT_RESPONSE_2"
        }
      ]
    },
