### ISSUE TITLE
Running install.sh after git clone requires over 200GB Ram

### ISSUE THREAD

**Issue by weicheng59** [OptimalScale/LMFlow#732]
I have a server with 128GB ram and it will be freeze when I follow the quick start procedure. On another server with 512GB ram it's fine. I think adding this warning in read.me could be helpful for other with limited ram.
Also, when I follow along the quick start procedure. I noticed I need to do 
```
pip install packaging
pip install torch
```
manually before install.sh can be successfully run.

**Comment by weicheng59** [comment]
The ram spike happaned in this stage before collecting numpy and other packages.
```
(lmflow) ai@server:~/llm/LMFlow$ bash install.sh
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Obtaining file:///home/asus/llm/LMFlow
  Preparing metadata (setup.py) ... done
```

**Comment by research4pan** [comment]
Thanks for reporting this issue! We will update the `README` accordingly to help others. Thanks for this meaningful contribution 👍

**Comment by weicheng59** [comment]
there seemed to be some confusion. I faced two issues.
1. You need to do 
```
pip install packaging
pip install torch
```
no matter you have limited ram or not. 

2. System with less than 200 GB ram can not use current install.sh to set up the environment.
In my case, if you have 128 GB ram, you just can not run the install.sh successfully. Your sever will freeze and you will notice ram is all used up. I guess after some really long hard disk swap (i waited for a hour but still not finish so i just restart the server and try it on a bigger ram machine), it can be installed but its not a good experience.

**Comment by research4pan** [comment]
Thanks for sharing more information! Let us update the document and dependency to reflect the change. Meanwhile, it can also be relevant to system versions and the local environment. Previously we have installed lmflow in Google Colab (with RAM 80G), which does not seem to have issues.

It would be greatly appreciated if you could share more information about the 128 GB system, and if possible, test if a similar problem occurs with other `pip` mirror sites. Thanks for your meaningful contribution!

**Comment by research4pan** [comment]
Thanks for your interest in LMFlow! It is possible that some dependency installation requires local compilation, which may consume a lot of memory. To check which package stuck the process, you may run `pip install -e .` or `pip install -r requirements.txt` to check. Thanks very much 😄
