### ISSUE TITLE
no data or dataset return

### ISSUE THREAD

**Issue by Alan-Qin** [OptimalScale/LMFlow#74]
After updating to the newest version of LMFlow, I met this problem (it does not happen before).

<img width="610" alt="image" src="https://user-images.githubusercontent.com/43122728/229442772-060ce059-e7f4-4c14-867a-46cb2eedb405.png">
My running code is:
<img width="403" alt="image" src="https://user-images.githubusercontent.com/43122728/229442894-dac0973d-e55d-466a-90e5-4e998a829eed.png">

Could you please help me figure it out?

Thanks

**Comment by shizhediao** [comment]
Great.
Nice to hear that. Thank you very much!

**Comment by shizhediao** [comment]
Hi Zeyu,
We have modified the README following your great suggestion! https://github.com/OptimalScale/LMFlow/pull/92

Thank you again!
