### ISSUE TITLE
Cannot open the address http://lmflow.org:5000

### ISSUE THREAD

**Issue by yiyiwwang** [OptimalScale/LMFlow#752]
I cannot open the address http://lmflow.org:5000 to download any available data with or without a VPN. Could you please check if the address is Okay? Thanks very much.

**Comment by research4pan** [comment]
Thanks for reporting this issue! We will check it right away.

**Comment by research4pan** [comment]
You may temporarily use http://107.23.182.175:5000/ for emergence use. We are fixing the domain name as well currently.

**Comment by research4pan** [comment]
The service is now recovered. Thanks very much for reporting this issue! 🤗

**Comment by yiyiwwang** [comment]
Thanks for your immediate reply and solutions!
