### ISSUE TITLE
after pip install -e . "fatal: unable to access 'https://github.com/huggingface/peft/': Failed to connect to github.com  Connection timed out"

### ISSUE THREAD

**Issue by gaohuiguo88** [OptimalScale/LMFlow#77]
After I input pip install -e . command, the system raises the error like the following:
"
Obtaining file:///home/huiguo/LMFlow
  Preparing metadata (setup.py) ... done
Collecting peft@ git+https://github.com/huggingface/peft@df0e1fb
  Cloning https://github.com/huggingface/peft (to revision df0e1fb) to /tmp/pip-install-dwdpzdhq/peft_7f8f6b97ae304fa699f8fb78c5fb0c5e
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/peft /tmp/pip-install-dwdpzdhq/peft_7f8f6b97ae304fa699f8fb78c5fb0c5e
  fatal: unable to access 'https://github.com/huggingface/peft/': Failed to connect to github.com port 443 after 129836 ms: Connection timed out
  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet https://github.com/huggingface/peft /tmp/pip-install-dwdpzdhq/peft_7f8f6b97ae304fa699f8fb78c5fb0c5e did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/huggingface/peft /tmp/pip-install-dwdpzdhq/peft_7f8f6b97ae304fa699f8fb78c5fb0c5e did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

"

**Comment by gaohuiguo88** [comment]
In brief, these commands work for me:
"
git config --global --add http.proxy http://127.0.0.1:7890
git config --global --add https.proxy http://127.0.0.1:7890
"

**Comment by wusijie123** [comment]
用服务器怎么查看代理端口？

**Comment by Gujing-Ace** [comment]
> 我遇上了这个问题,我是修改了git的代理端口,使其对上本机的手动代理端口而解决的,

请问可以具体说一下步骤吗，我修改端口没有起作用😭

**Comment by GXKIM** [comment]
我也是这个问题，服务器上安装的
