### ISSUE TITLE
ValueError: mutable default <class 'lmflow.utils.conversation_formatter.StringFormatter'> for field user_formatter is not allowed: use default_factory

### ISSUE THREAD

**Issue by 13416157913** [OptimalScale/LMFlow#795]
您好，我按照github上第三种微调方法，执行以下脚本，但是报错
./scripts/run_finetune_with_lora.sh \
  --model_name_or_path /home/dengkaibiao/Qwen1.5-1.8B \
  --dataset_path data/sft/train \
  --output_lora_path output_models/finetuned_Qwen1.5-1.8B_lora

报错信息：
Traceback (most recent call last):
  File "/home/dengkaibiao/LMFlow/examples/finetune.py", line 29, in <module>
    from lmflow.models.auto_model import AutoModel
  File "/home/dengkaibiao/LMFlow/src/lmflow/models/auto_model.py", line 6, in <module>
    from lmflow.models.hf_decoder_model import HFDecoderModel
  File "/home/dengkaibiao/LMFlow/src/lmflow/models/hf_decoder_model.py", line 62, in <module>
    from lmflow.utils.conversation_template import (
  File "/home/dengkaibiao/LMFlow/src/lmflow/utils/conversation_template.py", line 254, in <module>
    @dataclass
     ^^^^^^^^^
  File "/home/dengkaibiao/anaconda3/envs/lmflow/lib/python3.11/dataclasses.py", line 1232, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/home/dengkaibiao/anaconda3/envs/lmflow/lib/python3.11/dataclasses.py", line 1222, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dengkaibiao/anaconda3/envs/lmflow/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dengkaibiao/anaconda3/envs/lmflow/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'lmflow.utils.conversation_formatter.StringFormatter'> for field user_formatter is not allowed: use default_factory

**Comment by research4pan** [comment]
Thanks for your interest in LMFlow! We suspect it to be a problem caused by python version and dependency. You may try to use python3.9 and upgrade the `peft` package via `pip install -U peft`. We will make corresponding modifications later as well. Thanks for your valuable suggestions 😄

**Comment by 13416157913** [comment]
> Thanks for your interest in LMFlow! We suspect it to be a problem caused by python version and dependency. You may try to use python3.9 and upgrade the `peft` package via `pip install -U peft`. We will make corresponding modifications later as well. Thanks for your valuable suggestions 😄

Is it possible that it is because Qwen1.5-1.8B is not yet supported?

**Comment by 13416157913** [comment]
> Thanks for your interest in LMFlow! We suspect it to be a problem caused by python version and dependency. You may try to use python3.9 and upgrade the `peft` package via `pip install -U peft`. We will make corresponding modifications later as well. Thanks for your valuable suggestions 😄

pip install -U peft solved. Thanks a lot.

**Comment by 13416157913** [comment]
> > Thanks for your interest in LMFlow! We suspect it to be a problem caused by python version and dependency. You may try to use python3.9 and upgrade the `peft` package via `pip install -U peft`. We will make corresponding modifications later as well. Thanks for your valuable suggestions 😄
> 
> pip install -U peft solved. Thanks a lot. Sorry，I update peft from 0.4.0 to 0.10.0 meet same error.

![image](https://github.com/OptimalScale/LMFlow/assets/20581199/c40bc51c-9f10-41ec-8c67-184e9e747b6d)

**Comment by 13416157913** [comment]
> > > Thanks for your interest in LMFlow! We suspect it to be a problem caused by python version and dependency. You may try to use python3.9 and upgrade the `peft` package via `pip install -U peft`. We will make corresponding modifications later as well. Thanks for your valuable suggestions 😄
> > 
> > 
> > pip install -U peft solved. Thanks a lot. Sorry，I update peft from 0.4.0 to 0.10.0 meet same error.
> 
> ![image](https://private-user-images.githubusercontent.com/20581199/326313977-c40bc51c-9f10-41ec-8c67-184e9e747b6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNTU1NjksIm5iZiI6MTcxNDM1NTI2OSwicGF0aCI6Ii8yMDU4MTE5OS8zMjYzMTM5NzctYzQwYmM1MWMtOWYxMC00MWVjLThjNjctMTg0ZTllNzQ3YjZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDAxNDc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0N2JjYmMzMjE5NDk1MDY4ODFhYWYzNGIxZjM5NDBiNjRlMjZjOTJjMmYzZTg1Y2FmNGI1MjU5NWMzZjc2YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nq7MIlC0BzdWTYv-qBFVHoi3VQz1VlpSsYEh21-ccIQ)

![image](https://github.com/OptimalScale/LMFlow/assets/20581199/35b94dd9-f366-40b2-b47f-40e339a29d08)

**Comment by wheresmyhair** [comment]
Is there any library or package on your side that requires python 3.11? We recommend to use python 3.9, since we are developing LMFlow on that version. Python 3.9 works fine for me.
You could try:
```bash
git clone https://github.com/OptimalScale/LMFlow.git
cd LMFlow
conda create -n lmflow python=3.9 -y
conda activate lmflow
conda install mpi4py
bash install.sh
```
And we are working on solving conversation formatter dataclass issue for higher python versions. Sorry for the inconvenience.

**Comment by 13416157913** [comment]
> Is there any library or package on your side that requires python 3.11? We recommend to use python 3.9, since we are developing LMFlow on that version. Python 3.9 works fine for me. You could try:
> 
> ```shell
> git clone https://github.com/OptimalScale/LMFlow.git
> cd LMFlow
> conda create -n lmflow python=3.9 -y
> conda activate lmflow
> conda install mpi4py
> bash install.sh
> ```
> 
> And we are working on solving conversation formatter dataclass issue for higher python versions. Sorry for the inconvenience.

I have a try.

**Comment by 13416157913** [comment]
> Is there any library or package on your side that requires python 3.11? We recommend to use python 3.9, since we are developing LMFlow on that version. Python 3.9 works fine for me. You could try:
> 
> ```shell
> git clone https://github.com/OptimalScale/LMFlow.git
> cd LMFlow
> conda create -n lmflow python=3.9 -y
> conda activate lmflow
> conda install mpi4py
> bash install.sh
> ```
> 
> And we are working on solving conversation formatter dataclass issue for higher python versions. Sorry for the inconvenience.

conda create -n lmflow python=3.9 -y  the question was be solved. Thanks a lot.
