### ISSUE TITLE
Hello , Can LMFlow support Qwen1.5-1.8B model Fine-tuning?

### ISSUE THREAD

**Issue by 13416157913** [OptimalScale/LMFlow#796]
Hello , Can LMFlow support Qwen1.5-1.8B model Fine-tuning?

**Comment by research4pan** [comment]
Thanks for your interest in LMFlow! We are integrating that feature right now, hopefully supporting it in 1-2 days. Please stay tuned for our latest update 😄

**Comment by wheresmyhair** [comment]
> Hello , Can LMFlow support Qwen1.5-1.8B model Fine-tuning?

Hi, we've tested on Qwen1.5-1.8B and the script works fine. 
![qwen2](https://github.com/OptimalScale/LMFlow/assets/79436959/e5dee88a-ee9c-4b9c-a393-6392b74c4739)

Please make sure you include `--lora_target_modules q_proj, v_proj` in the finetune shell script:
![ft](https://github.com/OptimalScale/LMFlow/assets/79436959/81ecbc46-1941-4ca6-9d82-d8c632853182)

Also, we strongly recommend you to:
1. Use a conversation dataset to finetune the model. You could either:
	- To test the workflow, try to download a conversation dataset from out data server via:
		```bash
		cd data && ./download.sh alpaca && cd -
		``` 
		and specify the dataset to `data/alpaca/train_conversation`, or
	- Prepare your own conversation dataset (see [here](https://optimalscale.github.io/LMFlow/examples/DATASETS.html#conversation))
2. Specify the conversation template to `qwen2` for better performance.
