### ISSUE TITLE
error: PermissionError: [WinError 5] 拒绝访问。: '.\\deepspeed\\ops\\csrc'

### ISSUE THREAD

**Issue by natsukawa520** [OptimalScale/LMFlow#80]
你好.安装deepspeed==0.8.3的时候总是遇到这个错误,试着降下版本用了0.3.9安装没问题但是运行run_chatbot时弹出torch._six包不存在,请问下我该如何安装deepspeed最新版的,在windows上.谢谢.

**Comment by natsukawa520** [comment]
以下是全部错误的输出:
Collecting deepspeed==0.8.3
  Using cached deepspeed-0.8.3.tar.gz (765 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      系统找不到指定的文件。
      系统找不到指定的文件。
      fatal: not a git repository (or any of the parent directories): .git
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\79428\AppData\Local\Temp\pip-install-0p2oze8z\deepspeed_8ade02d1475540be9010c9fa62f63d92\setup.py", line 198, in <module>
          create_dir_symlink('..\\..\\csrc', '.\\deepspeed\\ops\\csrc')
        File "C:\Users\79428\AppData\Local\Temp\pip-install-0p2oze8z\deepspeed_8ade02d1475540be9010c9fa62f63d92\setup.py", line 190, in create_dir_symlink
          os.remove(dest)
      PermissionError: [WinError 5] 拒绝访问。: '.\\deepspeed\\ops\\csrc'
      DS_BUILD_OPS=1
      [93m [WARNING] [0m async_io requires the dev libaio .so object and headers but these were not found.
      [93m [WARNING] [0m If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
      [93m [WARNING] [0m cpu_adagrad requires the 'lscpu' command, but it does not exist!
      [93m [WARNING] [0m cpu_adagrad attempted to query 'lscpu' after failing to use py-cpuinfo to detect the CPU architecture. 'lscpu' does not appear to exist on your system, will fall back to use -march=native and non-vectorized execution.
      [93m [WARNING] [0m cpu_adagrad requires the 'lscpu' command, but it does not exist!
      [93m [WARNING] [0m cpu_adagrad attempted to query 'lscpu' after failing to use py-cpuinfo to detect the CPU architecture. 'lscpu' does not appear to exist on your system, will fall back to use -march=native and non-vectorized execution.
      [93m [WARNING] [0m sparse_attn requires a torch version >= 1.5 but detected 2.0
      [93m [WARNING] [0m please install triton==1.0.0 if you want to use sparse attention
      Install Ops={'async_io': False, 'cpu_adagrad': 1, 'cpu_adam': False, 'fused_adam': 1, 'fused_lamb': 1, 'quantizer': 1, 'random_ltd': 1, 'sparse_attn': False, 'spatial_inference': 1, 'transformer': 1, 'stochastic_transformer': 1, 'transformer_inference': 1, 'utils': 1}
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by shizhediao** [comment]
deepspeed最好是保持0.8.0以上的版本。
试试0.8.2可以吗，不行的话可以换一下安装源

**Comment by natsukawa520** [comment]
> 

谢谢反馈,0.8以上的版本都不行,我再尝试一下吧

**Comment by HelixPark** [comment]
ModuleNotFoundError: No module named 'torch._six'

见上，我也出现了这个错误，版本是0.8.0，

请问楼主解决了没

**Comment by natsukawa520** [comment]
> 

换成linux装新版大概就没问题了,这个应该是低版本的问题

**Comment by shizhediao** [comment]
感谢反馈！如果有问题欢迎继续交流~
