### ISSUE TITLE
how do you train the instruc-tuned model?

### ISSUE THREAD

**Issue by zixiliuUSC** [OptimalScale/LMFlow#85]
Do you train the models in model zoo in whole model finetune manner or in LoRA manner?
What data do you use in training Hu, Dongshan, Hetian and Altay??

**Comment by research4pan** [comment]
Thanks for your attention! We train all Hu, Dongshan, Hetian and Altay models in LoRA manner, with alpaca + https://huggingface.co/datasets/BelleGroup/train_0.5M_CN 😄 We are working on training better models with more datasets.
