### ISSUE TITLE
ValueError: Your setup doesn't support bf16/gpu. You need torch>=1.10, using Ampere GPU with cuda>=11.0

### ISSUE THREAD

**Issue by HelixPark** [OptimalScale/LMFlow#88]
GPU：2080Ti

**Comment by research4pan** [comment]
Hi, thanks for your attention. Currently bf16 is not supported by 2080 Ti, you may try fp16. Thanks 😄

**Comment by HelixPark** [comment]
if i modify the ds_config_zero3.json from bf16 to others, how it is work?

**Comment by research4pan** [comment]
It is unnecessary to modify the `ds_config_zero3.json` file. You can replace argument `--bf16` to `--fp16`, then it should work. Hope that solves your problem.

**Comment by HelixPark** [comment]
agree with you!  now it had been solved. 3Q!
